import { NextResponse } from "next/server";

import { resolvePromptTemplate } from "@/lib/ai-router/prompt-templates";
import { routeAiText } from "@/lib/ai-router/router";
import type { AiProviderSelection } from "@/lib/ai-router/types";
import { permissionError, resolvePermission } from "@/lib/team/permission-guards";

const provider = (value: unknown): AiProviderSelection => value === "openai" || value === "gemini" || value === "claude" ? value : "auto";
export async function POST(request:Request){const body=await request.json().catch(()=>({}))as Record<string,unknown>;const organizationId=typeof body.organizationId==="string"?body.organizationId:null;const access=await resolvePermission("content:edit",organizationId);if(!access.ok)return permissionError(access);const templateKey=typeof body.templateKey==="string"?body.templateKey.slice(0,100):null;const variables=body.variables&&typeof body.variables==="object"?body.variables as Record<string,unknown>:{};const template=templateKey?await resolvePromptTemplate(templateKey,variables,access.organizationId):null;if(templateKey&&!template)return NextResponse.json({error:"Prompt template not found."},{status:404});const prompt=template?.prompt??(typeof body.prompt==="string"?body.prompt.trim().slice(0,50000):"");if(!prompt)return NextResponse.json({error:"A prompt or prompt template is required."},{status:400});try{const result=await routeAiText({organizationId:access.organizationId,userId:access.user.id,endpoint:"/api/ai/generate",requestType:"generate",prompt,system:typeof body.system==="string"?body.system.slice(0,10000):template?.system,provider:body.provider?provider(body.provider):template?.provider??"auto",model:typeof body.model==="string"?body.model:undefined,promptTemplateKey:template?.key??null,metadata:{templateVersion:template?.version,variables:Object.keys(variables)}});return NextResponse.json(result);}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"AI generation failed."},{status:503});}}
