import "server-only";

import { routeAiText } from "@/lib/ai-router/router";
import type { ContentGenerationInput, ContentOutput } from "@/lib/content-ai/types";

const clean = (value: string, fallback: string) => value.trim() || fallback;
const slugWords = (value: string) => value.toLowerCase().replace(/[^a-z0-9\s]/g, " ").split(/\s+/).filter(Boolean);

function calendar(input: ContentGenerationInput) {
  const start = new Date(`${input.startDate || new Date().toISOString().slice(0, 10)}T12:00:00`);
  const days = Math.max(7, Math.min(30, input.days ?? 14));
  const formats = ["Educational reel", "Carousel", "Founder story", "Case study", "Quick tip", "Behind the scenes", "Community question"];
  return Array.from({ length: days }, (_, index) => {
    const date = new Date(start); date.setDate(start.getDate() + index);
    const format = formats[index % formats.length];
    return { date: date.toISOString().slice(0, 10), platform: input.platform || "Instagram", format, theme: `${input.topic}: ${format}`, hook: `What most ${input.audience || "customers"} miss about ${input.topic}`, cta: index % 2 ? "Save this for your next campaign." : `Reply “${slugWords(input.topic)[0] || "guide"}” for the framework.` };
  });
}

function localTemplate(input: ContentGenerationInput): ContentOutput {
  const topic = clean(input.topic, "your next growth opportunity");
  const brand = clean(input.brand, "the brand");
  const audience = clean(input.audience, "your ideal customer");
  const objective = clean(input.objective, "build trust and drive action");
  const tone = clean(input.tone, "confident and useful");
  if (input.type === "hook") return { title: `Hooks for ${topic}`, summary: `Ten ${tone} opening angles for ${audience}.`, sections: [{ heading: "Pattern interrupt hooks", content: [`Nobody tells ${audience} this about ${topic}.`, `Before you spend another rupee on ${topic}, watch this.`, `The fastest way to improve ${topic} is not what you think.`, `We tested the obvious advice about ${topic}. It failed.`, `Three signs your ${topic} strategy is costing you growth.`].join("\n") }, { heading: "Authority hooks", content: [`Here is the exact ${topic} framework ${brand} uses.`, `${topic} explained in 30 seconds—with no fluff.`, `Steal this simple system to ${objective}.`, `The one metric that changes how you approach ${topic}.`, `If we started ${topic} from zero today, we would do this.`].join("\n") }] };
  if (input.type === "caption") return { title: `${topic} caption set`, summary: `Platform-ready caption written in a ${tone} voice.`, sections: [{ heading: "Caption", content: `Most ${audience} do not need more information about ${topic}. They need a clear next move.\n\nAt ${brand}, we simplify the decision: identify the friction, show the proof, and make the action obvious. That is how you ${objective}.\n\nSave this, share it with your team, and tell us: what is the biggest ${topic} challenge you are solving right now?` }, { heading: "Short variant", content: `${topic} gets easier when the next step is obvious. Save this framework and put it to work this week.` }] };
  if (input.type === "hashtags") { const words = slugWords(`${topic} ${brand} ${audience}`); const tags = [...new Set(["contentstrategy", "digitalmarketing", "brandgrowth", "socialmediatips", ...words.map(word => word.slice(0, 24))])].slice(0, 15).map(word => `#${word}`); return { title: `Hashtag set for ${topic}`, summary: "A balanced mix of broad, niche, and branded discovery tags.", hashtags: tags, sections: [{ heading: "Recommended set", content: tags.join(" ") }, { heading: "Usage note", content: "Use 5–8 highly relevant tags per post and rotate niche tags to avoid repetitive distribution signals." }] }; }
  if (input.type === "thumbnail_concepts") return { title: `Thumbnail concepts: ${topic}`, summary: `Six high-contrast visual directions for ${input.platform || "social"}.`, sections: [{ heading: "Concepts", content: [`1. Before / After — split-screen transformation; text: “THE ${topic.toUpperCase()} FIX”`, `2. The Reveal — expressive close-up plus one obscured result; text: “WE TESTED IT”`, `3. Contrarian — crossed-out common advice; text: “STOP DOING THIS”`, `4. Proof Stack — bold result number with three supporting icons; text: “THE REAL NUMBERS”`, `5. Curiosity Gap — single object, dramatic crop; text: “THIS CHANGED EVERYTHING”`, `6. Blueprint — annotated framework on dark grid; text: “COPY THIS SYSTEM”`].join("\n\n") }, { heading: "Art direction", content: `Use ${brand}'s primary color as the focal accent, one face or object, no more than four words, and mobile-first contrast.` }] };
  if (input.type === "content_calendar") { const entries = calendar(input); return { title: `${input.days ?? 14}-day ${topic} calendar`, summary: `A balanced publishing cadence built to ${objective}.`, calendar: entries, sections: [{ heading: "Strategy", content: `Rotate education, proof, personality, and conversion posts. Use ${tone} language consistently and review saves, replies, and qualified clicks weekly.` }, { heading: "Cadence", content: `${entries.length} daily ideas beginning ${entries[0]?.date}, optimized for ${input.platform || "Instagram"}.` }] }; }
  if (input.type === "brand_analysis") return { title: `${brand} brand analysis`, summary: `${brand} can own a clearer position around ${topic} for ${audience}.`, sections: [{ heading: "Positioning", content: `Position ${brand} as the practical guide that turns ${topic} complexity into confident action. The promise should stay specific: ${objective}.` }, { heading: "Voice", content: `Lead with a ${tone} point of view. Prefer concrete examples, short claims, and transparent proof over broad superlatives.` }, { heading: "Content pillars", content: `1. Teach the system\n2. Show customer transformation\n3. Reveal the process\n4. Challenge category assumptions\n5. Invite low-friction action` }, { heading: "Risks and opportunities", content: `Risk: generic category language. Opportunity: build recognizable recurring formats and demonstrate proof earlier in every asset.` }, { heading: "90-day recommendation", content: `Publish three pillar series, document baseline metrics, interview five customers, and turn the strongest objection into a weekly signature format.` }] };
  if (input.type === "strategy_report") return { title: `${input.clientName || brand} content strategy`, summary: `A client-ready strategy to ${objective} with a repeatable ${input.platform || "multi-channel"} system.`, sections: [{ heading: "Executive summary", content: `${input.clientName || brand} should make ${topic} useful, recognizable, and easy to act on for ${audience}. The strategy combines authority-building education with proof-led conversion content.` }, { heading: "Audience insight", content: `${audience} wants clarity, evidence, and a next step. Content should name their tension before introducing the solution.` }, { heading: "Strategic pillars", content: `Educate: frameworks and practical guidance.\nProve: results, demonstrations, and case studies.\nHumanize: people, process, and point of view.\nConvert: objections, offers, and decisive CTAs.` }, { heading: "Channel plan", content: `${input.platform || "Instagram and LinkedIn"}: 3–5 posts weekly, one recurring flagship series, and one monthly proof-led campaign.` }, { heading: "Measurement", content: `Track qualified reach, saves, replies, profile actions, lead conversion, and assisted revenue. Review weekly signals and reset themes monthly.` }, { heading: "Next 30 days", content: `Finalize brand voice, produce the first 12 assets, launch two recurring formats, establish baseline conversion metrics, and review after four publishing cycles.` }] };
  return { title: `${topic} video script`, summary: `A concise ${tone} script designed to ${objective}.`, sections: [{ heading: "Hook (0–3s)", content: `If you are a ${audience} struggling with ${topic}, this is the part nobody explains.` }, { heading: "Setup (3–10s)", content: `Most advice gives you more tactics. The real problem is that the next action is not clear enough.` }, { heading: "Value (10–35s)", content: `Start with the one outcome your audience already wants. Show one concrete proof point. Then remove every step that does not help them decide. At ${brand}, we call this the clarity loop: tension, proof, action.` }, { heading: "Payoff (35–45s)", content: `When each piece does one job, ${topic} stops feeling complicated—and starts driving measurable progress.` }, { heading: "CTA", content: `Save this framework and send it to the person responsible for your next campaign.` }] };
}

function promptFor(input: ContentGenerationInput) {
  return `Create a ${input.type.replaceAll("_", " ")} for brand ${input.brand || "Unknown"}. Topic: ${input.topic}. Audience: ${input.audience}. Tone: ${input.tone}. Platform: ${input.platform}. Objective: ${input.objective}. Return polished, client-ready plain text with clear section headings. Do not mention being an AI.`;
}

export async function generateContent(input: ContentGenerationInput, context: { organizationId: string; userId: string }): Promise<{ output: ContentOutput; provider: "openai" | "gemini" | "claude"; model: string; prompt: string; fallbackCount: number }> {
  const prompt = promptFor(input);
  const result = await routeAiText({ organizationId: context.organizationId, userId: context.userId, endpoint: "/api/content-ai", requestType: "generate", prompt, system: "You are ReelMind's senior content strategist. Produce specific, useful agency-grade work.", provider: input.provider, promptTemplateKey: "content_generation", metadata: { contentType: input.type } });
  const structured = localTemplate(input);
  return { output: { title: structured.title, summary: `Generated by ${result.provider}${result.usage.fallbackCount ? ` after ${result.usage.fallbackCount} fallback attempt${result.usage.fallbackCount === 1 ? "" : "s"}` : ""}.`, sections: [{ heading: "Generated output", content: result.text }], ...(input.type === "content_calendar" ? { calendar: structured.calendar } : {}) }, provider: result.provider, model: result.model, prompt, fallbackCount: result.usage.fallbackCount };
}
