import type { ContentOutput } from "@/lib/content-ai/types";

const encode = (text: string) => new TextEncoder().encode(text);
const join = (parts: Uint8Array[]) => { const size = parts.reduce((sum, part) => sum + part.length, 0); const result = new Uint8Array(size); let offset = 0; parts.forEach(part => { result.set(part, offset); offset += part.length; }); return result; };
const safeName = (title: string) => title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60) || "reelmind-content";
const download = (bytes: Uint8Array, type: string, name: string) => { const buffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer; const url = URL.createObjectURL(new Blob([buffer], { type })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
const xml = (value: string) => value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const lines = (output: ContentOutput) => [output.title, output.summary, ...output.sections.flatMap(section => [section.heading, section.content]), ...(output.calendar ? ["Content Calendar", ...output.calendar.map(item => `${item.date} | ${item.platform} | ${item.format}\n${item.theme}\nHook: ${item.hook}\nCTA: ${item.cta}`)] : [])];

const crcTable = Array.from({ length: 256 }, (_, index) => { let value = index; for (let bit = 0; bit < 8; bit += 1) value = value & 1 ? 0xedb88320 ^ (value >>> 1) : value >>> 1; return value >>> 0; });
const crc32 = (bytes: Uint8Array) => { let crc = 0xffffffff; bytes.forEach(byte => { crc = crcTable[(crc ^ byte) & 0xff] ^ (crc >>> 8); }); return (crc ^ 0xffffffff) >>> 0; };
const u16 = (target: number[], value: number) => target.push(value & 255, value >>> 8 & 255);
const u32 = (target: number[], value: number) => target.push(value & 255, value >>> 8 & 255, value >>> 16 & 255, value >>> 24 & 255);
function zip(files: Array<{ name: string; bytes: Uint8Array }>) { const locals: Uint8Array[] = []; const central: Uint8Array[] = []; let offset = 0; files.forEach(file => { const name = encode(file.name); const crc = crc32(file.bytes); const local: number[] = []; u32(local, 0x04034b50); u16(local, 20); u16(local, 0); u16(local, 0); u16(local, 0); u16(local, 0); u32(local, crc); u32(local, file.bytes.length); u32(local, file.bytes.length); u16(local, name.length); u16(local, 0); const part = join([new Uint8Array(local), name, file.bytes]); locals.push(part); const header: number[] = []; u32(header, 0x02014b50); u16(header, 20); u16(header, 20); u16(header, 0); u16(header, 0); u16(header, 0); u16(header, 0); u32(header, crc); u32(header, file.bytes.length); u32(header, file.bytes.length); u16(header, name.length); u16(header, 0); u16(header, 0); u16(header, 0); u16(header, 0); u32(header, 0); u32(header, offset); central.push(join([new Uint8Array(header), name])); offset += part.length; }); const directory = join(central); const end: number[] = []; u32(end, 0x06054b50); u16(end, 0); u16(end, 0); u16(end, files.length); u16(end, files.length); u32(end, directory.length); u32(end, offset); u16(end, 0); return join([...locals, directory, new Uint8Array(end)]); }

export function downloadDocx(output: ContentOutput) {
  const paragraphs = lines(output).flatMap((value, index) => value.split("\n").map(line => `<w:p><w:pPr>${index === 0 ? '<w:pStyle w:val="Title"/>' : index === 2 || output.sections.some(section => section.heading === value) ? '<w:pStyle w:val="Heading1"/>' : ""}</w:pPr><w:r><w:t xml:space="preserve">${xml(line)}</w:t></w:r></w:p>`)).join("");
  const document = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${paragraphs}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134"/></w:sectPr></w:body></w:document>`;
  const styles = `<?xml version="1.0" encoding="UTF-8"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:rPr><w:b/><w:sz w:val="36"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:rPr><w:b/><w:color w:val="2563EB"/><w:sz w:val="26"/></w:rPr></w:style></w:styles>`;
  const bytes = zip([{ name: "[Content_Types].xml", bytes: encode(`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>`) }, { name: "_rels/.rels", bytes: encode(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`) }, { name: "word/document.xml", bytes: encode(document) }, { name: "word/styles.xml", bytes: encode(styles) }, { name: "word/_rels/document.xml.rels", bytes: encode(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`) }]);
  download(bytes, "application/vnd.openxmlformats-officedocument.wordprocessingml.document", `${safeName(output.title)}.docx`);
}

export function downloadPdf(output: ContentOutput) {
  const canvas = document.createElement("canvas"); canvas.width = 1240; canvas.height = 1754; const ctx = canvas.getContext("2d"); if (!ctx) throw new Error("Canvas unavailable"); ctx.fillStyle = "#07111f"; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = "#38bdf8"; ctx.font = "700 26px Arial"; ctx.fillText("REELMIND AI • CONTENT STUDIO", 72, 80); let y = 145; const drawWrapped = (text: string, font: string, color: string, gap: number) => { ctx.font = font; ctx.fillStyle = color; const words = text.split(/\s+/); let line = ""; for (const word of words) { const next = `${line} ${word}`.trim(); if (ctx.measureText(next).width > 1090) { ctx.fillText(line, 72, y); y += gap; line = word; } else line = next; } if (line) { ctx.fillText(line, 72, y); y += gap; } };
  drawWrapped(output.title, "700 44px Arial", "#f8fafc", 56); y += 14; drawWrapped(output.summary, "400 24px Arial", "#94a3b8", 34); for (const section of output.sections) { y += 26; if (y > 1600) break; drawWrapped(section.heading, "700 28px Arial", "#a855f7", 38); section.content.split("\n").forEach(line => drawWrapped(line || " ", "400 21px Arial", "#e2e8f0", 31)); } const jpeg = atob(canvas.toDataURL("image/jpeg", .92).split(",")[1]); const image = Uint8Array.from(jpeg, char => char.charCodeAt(0)); const parts: Uint8Array[] = []; const offsets = [0]; let position = 0; const add = (part: Uint8Array) => { parts.push(part); position += part.length; }; const object = (id: number, body: Uint8Array[]) => { offsets[id] = position; add(encode(`${id} 0 obj\n`)); body.forEach(add); add(encode("\nendobj\n")); }; add(encode("%PDF-1.4\n")); object(1, [encode("<< /Type /Catalog /Pages 2 0 R >>")]); object(2, [encode("<< /Type /Pages /Kids [5 0 R] /Count 1 >>")]); object(3, [encode(`<< /Type /XObject /Subtype /Image /Width 1240 /Height 1754 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${image.length} >>\nstream\n`), image, encode("\nendstream")]); const stream = encode("q 595 0 0 842 0 0 cm /Im0 Do Q"); object(4, [encode(`<< /Length ${stream.length} >>\nstream\n`), stream, encode("\nendstream")]); object(5, [encode("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im0 3 0 R >> >> /Contents 4 0 R >>")]); const xref = position; add(encode(`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(value => `${String(value).padStart(10, "0")} 00000 n \n`).join("")}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`)); download(join(parts), "application/pdf", `${safeName(output.title)}.pdf`);
}
