import "server-only";
import { createAdminClient } from "@/lib/supabase/admin";
import type { AgencySnapshot, AiAgentType } from "@/lib/ai-agency/types";

type Project = { id:string; client_name:string; client_email:string|null; project_title:string; project_description:string|null; status:string; priority:string; deadline:string|null; assigned_to:string|null; updated_at:string };
type Lead = { id:string; name:string; email:string|null; phone:string|null; source:string|null; budget:number|string|null; notes:string|null; status:string; created_at:string; updated_at:string };
type Invoice = { id:string; project_id:string; invoice_number:string|null; amount:number|string; status:string; issued_at:string; paid_at:string|null };
const agentDefinitions: Array<{ type: AiAgentType; name: string; description: string }> = [
  { type:"project_manager", name:"AI Project Manager", description:"Monitors delivery risk, deadlines, assignment gaps, and project momentum." },
  { type:"sales_agent", name:"AI Sales Agent", description:"Scores leads and surfaces the next best sales follow-up." },
  { type:"client_success", name:"AI Client Success Agent", description:"Tracks client health, approvals, delivery, and payment friction." },
  { type:"content_strategist", name:"AI Content Strategist", description:"Suggests content angles and production priorities from live briefs." },
  { type:"workspace_copilot", name:"AI Workspace Copilot", description:"Answers operational questions from current workspace data." },
];
const clamp = (value:number) => Math.max(0, Math.min(100, Math.round(value)));
const daysFromNow = (date:string) => Math.ceil((new Date(date).getTime() - Date.now()) / 86400000);
const staleDays = (date:string) => Math.floor((Date.now() - new Date(date).getTime()) / 86400000);

export async function ensureAiAgents(organizationId:string) {
  const admin = createAdminClient();
  await admin.from("ai_agents").upsert(agentDefinitions.map(agent => ({ organization_id:organizationId, agent_type:agent.type, name:agent.name, description:agent.description, status:"active", updated_at:new Date().toISOString() })), { onConflict:"organization_id,agent_type" });
  const { data, error } = await admin.from("ai_agents").select("id,agent_type,name,description,status,last_run_at").eq("organization_id",organizationId).order("created_at");
  if (error) throw error; return data ?? [];
}

export async function buildAgencySnapshot(organizationId:string): Promise<AgencySnapshot> {
  const admin = createAdminClient();
  const [projectResult, leadResult, invoiceResult] = await Promise.all([
    admin.from("client_projects").select("id,client_name,client_email,project_title,project_description,status,priority,deadline,assigned_to,updated_at").eq("organization_id",organizationId),
    admin.from("leads").select("id,name,email,phone,source,budget,notes,status,created_at,updated_at").eq("organization_id",organizationId),
    admin.from("project_invoices").select("id,project_id,invoice_number,amount,status,issued_at,paid_at").eq("organization_id",organizationId),
  ]);
  const projects=(projectResult.data??[]) as Project[]; const leads=(leadResult.data??[]) as Lead[]; const invoices=(invoiceResult.data??[]) as Invoice[];
  const openProjects=projects.filter(p=>!["delivered","archived"].includes(p.status));
  const projectRisks=openProjects.map(project=>{ let score=15; const reasons:string[]=[]; if(!project.assigned_to){score+=25;reasons.push("unassigned");} if(project.priority==="urgent"){score+=20;reasons.push("urgent");} else if(project.priority==="high")score+=10; if(project.deadline){const days=daysFromNow(project.deadline); if(days<0){score+=35;reasons.push(`${Math.abs(days)}d overdue`);} else if(days<=3){score+=20;reasons.push(`due in ${days}d`);}} if(staleDays(project.updated_at)>7){score+=15;reasons.push("no update in 7d+");} if(project.status==="review") { score+=8; reasons.push("awaiting review"); } return {id:project.id,title:project.project_title,client:project.client_name,status:project.status,score:clamp(score),reason:reasons.join(", ")||"on track"};}).sort((a,b)=>b.score-a.score);
  const leadScores=leads.filter(l=>!["won","lost"].includes(l.status)).map(lead=>{let score=20;const reasons:string[]=[];const stage:Record<string,number>={new:0,qualified:25,proposal:40,negotiation:55};score+=stage[lead.status]??0;if(lead.email){score+=8;reasons.push("email available");}if(lead.phone){score+=7;reasons.push("phone available");}const budget=Number(lead.budget??0);if(budget>=5000){score+=15;reasons.push("high budget");}else if(budget>0)score+=8;if(staleDays(lead.updated_at)>7){score-=15;reasons.push("follow-up overdue");}return{id:lead.id,name:lead.name,status:lead.status,score:clamp(score),reason:reasons.join(", ")||"early-stage lead"};}).sort((a,b)=>b.score-a.score);
  const clients=new Map<string,{projects:Project[];invoices:Invoice[]}>();projects.forEach(p=>{const key=p.client_email||p.client_name;const current=clients.get(key)??{projects:[],invoices:[]};current.projects.push(p);current.invoices.push(...invoices.filter(i=>i.project_id===p.id));clients.set(key,current);});
  const clientHealth=[...clients.entries()].map(([client,data])=>{let score=85;const reasons:string[]=[];const overdue=data.projects.filter(p=>p.deadline&&daysFromNow(p.deadline)<0&&p.status!=="delivered").length;const unpaid=data.invoices.filter(i=>["pending","partially_paid"].includes(i.status)).length;if(overdue){score-=overdue*18;reasons.push(`${overdue} delayed project${overdue>1?"s":""}`);}if(unpaid){score-=unpaid*12;reasons.push(`${unpaid} unpaid invoice${unpaid>1?"s":""}`);}if(data.projects.some(p=>p.status==="review")){score-=8;reasons.push("approval pending");}if(data.projects.some(p=>p.status==="delivered")){score+=8;reasons.push("delivery completed");}return{client,score:clamp(score),reason:reasons.join(", ")||"healthy engagement"};}).sort((a,b)=>a.score-b.score);
  const paid=invoices.filter(i=>i.status==="paid").reduce((sum,i)=>sum+Number(i.amount),0);const unpaid=invoices.filter(i=>["pending","partially_paid"].includes(i.status));const won=leads.filter(l=>l.status==="won").length;
  return {revenue:paid,pendingRevenue:unpaid.reduce((sum,i)=>sum+Number(i.amount),0),activeClients:new Set(openProjects.map(p=>p.client_email||p.client_name)).size,activeProjects:openProjects.length,delayedProjects:projectRisks.filter(p=>p.reason.includes("overdue")).length,unpaidInvoices:unpaid.length,unpaidAmount:unpaid.reduce((sum,i)=>sum+Number(i.amount),0),totalLeads:leads.length,wonLeads:won,leadConversionRate:leads.length?Math.round(won/leads.length*100):0,leadScores,projectRisks,clientHealth};
}

export async function generateAiAgencyInsights(organizationId:string,userId:string) {
  const admin=createAdminClient();const agents=await ensureAiAgents(organizationId);const byType=new Map(agents.map(agent=>[agent.agent_type,agent]));const snapshot=await buildAgencySnapshot(organizationId);const recommendations:Array<Record<string,unknown>>=[];const tasks:Array<Record<string,unknown>>=[];
  snapshot.projectRisks.slice(0,5).forEach(risk=>{recommendations.push({organization_id:organizationId,agent_id:byType.get("project_manager")?.id,project_id:risk.id,recommendation_type:"project_risk",title:`${risk.title}: ${risk.score}% risk`,recommendation:risk.score>=60?`Intervene now: ${risk.reason}. Confirm ownership and reset the next milestone.`:`Keep momentum visible: ${risk.reason}.`,score:risk.score,severity:risk.score>=75?"critical":risk.score>=55?"warning":"info",metadata:risk});if(risk.score>=55)tasks.push({organization_id:organizationId,agent_id:byType.get("project_manager")?.id,project_id:risk.id,title:`De-risk ${risk.title}`,description:risk.reason,priority:risk.score>=75?"urgent":"high",metadata:{score:risk.score}});});
  snapshot.leadScores.slice(0,5).forEach(lead=>{recommendations.push({organization_id:organizationId,agent_id:byType.get("sales_agent")?.id,lead_id:lead.id,recommendation_type:"lead_score",title:`${lead.name}: ${lead.score}% fit`,recommendation:lead.score>=65?`Prioritize a personal follow-up. ${lead.reason}.`:`Nurture with a relevant proof point before pushing for a call. ${lead.reason}.`,score:lead.score,severity:lead.score>=65?"opportunity":"info",metadata:lead});if(lead.score>=60)tasks.push({organization_id:organizationId,agent_id:byType.get("sales_agent")?.id,lead_id:lead.id,title:`Follow up with ${lead.name}`,description:`Lead score ${lead.score}. ${lead.reason}`,priority:lead.score>=80?"high":"medium",metadata:{score:lead.score}});});
  snapshot.clientHealth.slice(0,5).forEach(client=>recommendations.push({organization_id:organizationId,agent_id:byType.get("client_success")?.id,recommendation_type:"client_health",title:`${client.client}: ${client.score}% health`,recommendation:client.score<60?`Schedule a recovery check-in: ${client.reason}.`:`Maintain the relationship cadence: ${client.reason}.`,score:client.score,severity:client.score<45?"critical":client.score<70?"warning":"info",metadata:client}));
  const {data:contentProjects}=await admin.from("client_projects").select("id,project_title,project_description,status,priority").eq("organization_id",organizationId).in("status",["brief","planning","scripting"]).order("updated_at",{ascending:false}).limit(5);(contentProjects??[]).forEach(project=>recommendations.push({organization_id:organizationId,agent_id:byType.get("content_strategist")?.id,project_id:project.id,recommendation_type:"content_suggestion",title:`Content direction for ${project.project_title}`,recommendation:`Build the opening around the client's strongest tension, add one concrete proof point, and end with a single low-friction CTA.${project.project_description?` Brief context: ${String(project.project_description).slice(0,140)}`:""}`,severity:"opportunity",metadata:{status:project.status,priority:project.priority}}));
  await Promise.all([admin.from("ai_recommendations").delete().eq("organization_id",organizationId).eq("status","open"),admin.from("ai_tasks").delete().eq("organization_id",organizationId).eq("status","suggested")]);if(recommendations.length)await admin.from("ai_recommendations").insert(recommendations);if(tasks.length)await admin.from("ai_tasks").insert(tasks);await admin.from("ai_agents").update({last_run_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("organization_id",organizationId);await admin.from("team_activity_logs").insert({organization_id:organizationId,user_id:userId,action:"ai_recommendations_generated",metadata:{recommendationCount:recommendations.length,taskCount:tasks.length}});return snapshot;
}

export function answerCopilot(question:string,snapshot:AgencySnapshot){const q=question.toLowerCase();const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);if(q.includes("revenue"))return `Paid revenue is ${money(snapshot.revenue)}. Another ${money(snapshot.pendingRevenue)} is outstanding.`;if(q.includes("active client"))return `You have ${snapshot.activeClients} active clients across ${snapshot.activeProjects} active projects.`;if(q.includes("delayed")||q.includes("overdue"))return snapshot.delayedProjects?`${snapshot.delayedProjects} projects are delayed. Highest risk: ${snapshot.projectRisks.slice(0,3).map(p=>`${p.title} (${p.score}%)`).join(", ")}.`:"No projects are currently past their deadline.";if(q.includes("unpaid")||q.includes("invoice"))return `${snapshot.unpaidInvoices} invoices are unpaid, totaling ${money(snapshot.unpaidAmount)}.`;if(q.includes("conversion")||q.includes("lead"))return `Lead conversion is ${snapshot.leadConversionRate}% (${snapshot.wonLeads} won from ${snapshot.totalLeads} total leads).`;return `Right now: ${money(snapshot.revenue)} paid revenue, ${snapshot.activeClients} active clients, ${snapshot.delayedProjects} delayed projects, ${snapshot.unpaidInvoices} unpaid invoices, and ${snapshot.leadConversionRate}% lead conversion.`;}
