import "server-only";
import { createAdminClient } from "@/lib/supabase/admin";
import { decryptSecret } from "@/lib/whatsapp/crypto";
import type { WhatsAppEventPayload,WhatsAppTriggerEvent } from "@/lib/whatsapp/types";

type Connection={id:string;organization_id:string;phone_number_id:string;access_token_encrypted:string;status:string};
type Template={name:string;meta_template_name:string|null;language:string;body:string;status:string};
export function normalizePhone(value:string){return value.replace(/[^0-9]/g,"");}
const graphVersion=()=>process.env.WHATSAPP_GRAPH_API_VERSION||"v22.0";
const text=(value:unknown)=>value===null||value===undefined?"":String(value);
export function interpolateWhatsApp(body:string,payload:WhatsAppEventPayload){return body.replace(/\{\{(\w+)\}\}/g,(_match,key:string)=>text(payload[key]));}

async function sendCloud(connection:Connection,to:string,body:string,template?:Template|null,templateParameters:string[]=[]){const token=decryptSecret(connection.access_token_encrypted);let message:Record<string,unknown>={messaging_product:"whatsapp",recipient_type:"individual",to:normalizePhone(to),type:"text",text:{preview_url:false,body}};if(template?.status==="approved"&&template.meta_template_name){message={messaging_product:"whatsapp",to:normalizePhone(to),type:"template",template:{name:template.meta_template_name,language:{code:template.language},components:templateParameters.length?[{type:"body",parameters:templateParameters.map(parameter=>({type:"text",text:parameter}))}]:undefined}};}const response=await fetch(`https://graph.facebook.com/${graphVersion()}/${connection.phone_number_id}/messages`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(message)});const result=await response.json() as{messages?:Array<{id:string}>;error?:{message?:string}};if(!response.ok)throw new Error(result.error?.message||`WhatsApp API returned ${response.status}.`);return result.messages?.[0]?.id??null;}

export async function sendWhatsAppText(input:{organizationId:string;to:string;body:string;projectId?:string|null;leadId?:string|null;triggerEvent?:string|null;template?:Template|null;templateParameters?:string[];contactName?:string|null}){const admin=createAdminClient();const{data:connection,error:connectionError}=await admin.from("whatsapp_connections").select("id,organization_id,phone_number_id,access_token_encrypted,status").eq("organization_id",input.organizationId).eq("status","active").maybeSingle();if(connectionError||!connection)throw new Error(connectionError?.message||"WhatsApp is not connected.");const phone=normalizePhone(input.to);const{data:message,error}=await admin.from("whatsapp_messages").insert({organization_id:input.organizationId,connection_id:connection.id,project_id:input.projectId??null,lead_id:input.leadId??null,direction:"outbound",message_type:input.template?.meta_template_name?"template":"text",contact_phone:phone,contact_name:input.contactName??null,body:input.body,status:"queued",template_name:input.template?.name??null,trigger_event:input.triggerEvent??null}).select("id").single();if(error)throw error;try{const externalId=await sendCloud(connection as Connection,phone,input.body,input.template,input.templateParameters);await admin.from("whatsapp_messages").update({whatsapp_message_id:externalId,status:"sent",sent_at:new Date().toISOString()}).eq("id",message.id);return{messageId:message.id,whatsappMessageId:externalId};}catch(error){const reason=error instanceof Error?error.message:"WhatsApp send failed.";await admin.from("whatsapp_messages").update({status:"failed",error_message:reason}).eq("id",message.id);throw error;}}

export async function notifyWhatsAppEvent(organizationId:string,event:WhatsAppTriggerEvent,payload:WhatsAppEventPayload){try{const phone=payload.phone?String(payload.phone):"";if(!normalizePhone(phone))return null;const admin=createAdminClient();const{data:template}=await admin.from("whatsapp_templates").select("name,meta_template_name,language,body,status").eq("organization_id",organizationId).eq("trigger_event",event).eq("is_automatic",true).neq("status","disabled").limit(1).maybeSingle();if(!template)return null;const values:WhatsAppEventPayload={...payload,agencyName:payload.agencyName??"our agency"};const body=interpolateWhatsApp(template.body,values);const keys=[...template.body.matchAll(/\{\{(\w+)\}\}/g)].map(match=>match[1]);const result=await sendWhatsAppText({organizationId,to:phone,body,projectId:payload.projectId??null,leadId:payload.leadId??null,triggerEvent:event,template:template as Template,templateParameters:keys.map(key=>text(values[key])),contactName:payload.name??null});await admin.from("team_activity_logs").insert({organization_id:organizationId,user_id:null,action:"whatsapp_auto_notification_sent",metadata:{event,phone:normalizePhone(phone),messageId:result.messageId}});return result;}catch(error){console.error("[whatsapp] automatic notification failed",{organizationId,event,error});return null;}}

export async function scanOverdueInvoices(organizationId:string){const admin=createAdminClient();const{data:invoices}=await admin.from("project_invoices").select("id,project_id,invoice_number,amount,currency,issued_at,project:client_projects(client_name,client_phone)").eq("organization_id",organizationId).in("status",["pending","partially_paid"]).lt("issued_at",new Date(Date.now()-7*86400000).toISOString());let sent=0;for(const invoice of invoices??[]){const{count}=await admin.from("whatsapp_messages").select("id",{count:"exact",head:true}).eq("organization_id",organizationId).eq("trigger_event","invoice_overdue").contains("metadata",{invoiceId:invoice.id});if(count)continue;const project=Array.isArray(invoice.project)?invoice.project[0]:invoice.project;const result=await notifyWhatsAppEvent(organizationId,"invoice_overdue",{phone:project?.client_phone,projectId:invoice.project_id,name:project?.client_name,invoiceNumber:invoice.invoice_number,amount:`${invoice.currency} ${invoice.amount}`});if(result){sent+=1;await admin.from("whatsapp_messages").update({metadata:{invoiceId:invoice.id}}).eq("id",result.messageId);}}return sent;}

export function suggestWhatsAppReply(body:string){const value=body.trim().toLowerCase();if(value.includes("when")||value.includes("update"))return{reply:"Thanks for checking in. I’m reviewing the latest project update and will confirm the next milestone shortly.",followUp:"Confirm the project owner and next delivery date."};if(value.includes("invoice")||value.includes("payment"))return{reply:"I’ll check the latest invoice status and share the details with you.",followUp:"Review outstanding invoice and payment notes."};if(value.includes("change")||value.includes("revision"))return{reply:"Thanks for the clear feedback. I’ve noted the revision request and the team will review it next.",followUp:"Convert the message into a project revision task."};return{reply:"Thanks for your message. We’ve received it and will get back to you with a clear next step.",followUp:"Reply within the current client response window."};}
