import { NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { permissionError,resolvePermission } from "@/lib/team/permission-guards";
import { encryptSecret,hashToken } from "@/lib/whatsapp/crypto";
import { scanOverdueInvoices,sendWhatsAppText } from "@/lib/whatsapp/service";
import { whatsappTriggerEvents } from "@/lib/whatsapp/types";

const clean=(value:unknown,max=500)=>typeof value==="string"?value.trim().slice(0,max):"";
const defaults=[
 ["Lead welcome","Hi {{name}}, thanks for contacting {{agencyName}}. We have your request and will follow up shortly.","lead_created"],["Lead assigned","Hi {{name}}, your inquiry has been assigned to our team.","lead_assigned"],["Project assigned","Your project {{projectTitle}} has been assigned and is moving forward.","project_assigned"],["Review requested","{{projectTitle}} is ready for your review. Reply status for the latest update.","review_requested"],["Project approved","Thanks for approving {{projectTitle}}. We are preparing final delivery.","project_approved"],["Invoice created","Invoice {{invoiceNumber}} for {{amount}} is ready. Reply invoice for details.","invoice_created"],["Invoice overdue","A reminder that invoice {{invoiceNumber}} for {{amount}} is overdue.","invoice_overdue"],["Payment received","Payment received for {{invoiceNumber}}. Thank you.","payment_received"],["Project delivered","{{projectTitle}} has been delivered. Reply files for delivery details.","project_delivered"]
] as const;
async function ensureTemplates(organizationId:string){const admin=createAdminClient();await admin.from("whatsapp_templates").upsert(defaults.map(([name,body,trigger_event])=>({organization_id:organizationId,name,body,trigger_event,language:"en_US",category:"UTILITY",status:"draft",is_automatic:false})),{onConflict:"organization_id,name,language",ignoreDuplicates:true});}

export async function GET(request:Request){const organizationId=new URL(request.url).searchParams.get("organizationId");const access=await resolvePermission("projects:manage",organizationId);if(!access.ok)return permissionError(access);await ensureTemplates(access.organizationId);const admin=createAdminClient();const[connection,messages,templates]=await Promise.all([admin.from("whatsapp_connections").select("id,business_account_id,phone_number_id,display_phone_number,status,last_webhook_at,created_at,updated_at").eq("organization_id",access.organizationId).maybeSingle(),admin.from("whatsapp_messages").select("id,project_id,lead_id,whatsapp_message_id,direction,message_type,contact_phone,contact_name,body,status,template_name,trigger_event,error_message,metadata,sent_at,delivered_at,read_at,created_at").eq("organization_id",access.organizationId).order("created_at",{ascending:false}).limit(100),admin.from("whatsapp_templates").select("id,name,meta_template_name,language,category,body,trigger_event,is_automatic,status,updated_at").eq("organization_id",access.organizationId).order("name")]);return NextResponse.json({connection:connection.data??null,messages:messages.data??[],templates:templates.data??[],webhookUrl:`${process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/,"")??""}/api/whatsapp/webhook`,canConfigure:["owner","admin"].includes(access.role)});}

export async function POST(request:Request){const body=await request.json().catch(()=>({})) as Record<string,unknown>;const organizationId=clean(body.organizationId,64);const operation=clean(body.operation,40);const permission=operation==="connect"||operation==="template"||operation==="disconnect"?"settings:manage":"projects:manage";const access=await resolvePermission(permission,organizationId);if(!access.ok)return permissionError(access);const admin=createAdminClient();
  if(operation==="connect"){const businessAccountId=clean(body.businessAccountId,100);const phoneNumberId=clean(body.phoneNumberId,100);const accessToken=clean(body.accessToken,2000);const appSecret=clean(body.appSecret,500);const verifyToken=clean(body.verifyToken,500);if(!businessAccountId||!phoneNumberId||!accessToken||!appSecret||!verifyToken)return NextResponse.json({error:"Business account, phone number ID, access token, app secret, and verify token are required."},{status:400});const version=process.env.WHATSAPP_GRAPH_API_VERSION||"v22.0";const test=await fetch(`https://graph.facebook.com/${version}/${phoneNumberId}?fields=display_phone_number,verified_name`,{headers:{Authorization:`Bearer ${accessToken}`}});const result=await test.json() as{display_phone_number?:string;error?:{message?:string}};if(!test.ok)return NextResponse.json({error:result.error?.message||"Meta could not verify this phone number ID."},{status:400});const{error}=await admin.from("whatsapp_connections").upsert({organization_id:organizationId,business_account_id:businessAccountId,phone_number_id:phoneNumberId,display_phone_number:result.display_phone_number??null,access_token_encrypted:encryptSecret(accessToken),app_secret_encrypted:encryptSecret(appSecret),verify_token_hash:hashToken(verifyToken),status:"active",created_by:access.user.id,updated_at:new Date().toISOString()},{onConflict:"organization_id"});if(error)return NextResponse.json({error:error.message},{status:400});await ensureTemplates(organizationId);await admin.from("team_activity_logs").insert({organization_id:organizationId,user_id:access.user.id,action:"whatsapp_connected",metadata:{phoneNumberId,businessAccountId}});return NextResponse.json({success:true});}
  if(operation==="send"){const to=clean(body.to,40);const message=clean(body.message,4096);if(!to||!message)return NextResponse.json({error:"Recipient and message are required."},{status:400});try{const result=await sendWhatsAppText({organizationId,to,body:message});await admin.from("team_activity_logs").insert({organization_id:organizationId,user_id:access.user.id,action:"whatsapp_message_sent",metadata:{messageId:result.messageId,to}});return NextResponse.json({success:true,...result});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Message failed."},{status:400});}}
  if(operation==="template"){const id=clean(body.id,64);const name=clean(body.name,120);const templateBody=clean(body.body,4096);const triggerEvent=clean(body.triggerEvent,50);const language=clean(body.language,20)||"en_US";const status=clean(body.status,20)||"draft";const metaTemplateName=clean(body.metaTemplateName,200)||null;const isAutomatic=body.isAutomatic===true;if(!name||!templateBody||(triggerEvent&&!(whatsappTriggerEvents as readonly string[]).includes(triggerEvent)))return NextResponse.json({error:"Template name, body, and valid trigger are required."},{status:400});const values={organization_id:organizationId,name,body:templateBody,trigger_event:triggerEvent||null,language,category:"UTILITY",status,meta_template_name:metaTemplateName,is_automatic:isAutomatic,updated_at:new Date().toISOString()};const query=id?admin.from("whatsapp_templates").update(values).eq("id",id).eq("organization_id",organizationId):admin.from("whatsapp_templates").insert(values);const{error}=await query;if(error)return NextResponse.json({error:error.message},{status:400});await admin.from("team_activity_logs").insert({organization_id:organizationId,user_id:access.user.id,action:"whatsapp_template_updated",metadata:{templateId:id||null,name,triggerEvent,isAutomatic}});return NextResponse.json({success:true});}
  if(operation==="scan_overdue"){const sent=await scanOverdueInvoices(organizationId);await admin.from("team_activity_logs").insert({organization_id:organizationId,user_id:access.user.id,action:"whatsapp_overdue_scan",metadata:{sent}});return NextResponse.json({success:true,sent});}
  if(operation==="disconnect"){await admin.from("whatsapp_connections").update({status:"disconnected",updated_at:new Date().toISOString()}).eq("organization_id",organizationId);await admin.from("team_activity_logs").insert({organization_id:organizationId,user_id:access.user.id,action:"whatsapp_disconnected",metadata:{}});return NextResponse.json({success:true});}
  return NextResponse.json({error:"Unsupported operation."},{status:400});}
