"use client";

import Link from "next/link";
import { useCallback,useEffect,useState } from "react";

type Provider={provider:string;name:string;configured:boolean;missing:string[];defaultModel:string;status:string;lastCheckedAt:string|null;lastSuccessAt:string|null;latencyMs:number|null;consecutiveFailures:number;lastError:string|null;totalRequests:number;totalFailures:number};
type ProviderUsage={provider:string;requests:number;tokens:number;costUsd:number;errors:number;averageLatencyMs:number};
type Daily={date:string;requests:number;tokens:number;costUsd:number;errors:number};
type Log={id:string;request_id:string;endpoint:string;request_type:string;requested_provider:string;provider_used:string|null;model:string|null;status:string;fallback_count:number;total_tokens:number;estimated_cost_usd:number;latency_ms:number;error_message:string|null;created_at:string};
type Data={days:number;metrics:{requests:number;totalTokens:number;costUsd:number;errorRate:number;fallbackRate:number;averageLatencyMs:number};providers:Provider[];providerUsage:ProviderUsage[];daily:Daily[];logs:Log[]};
const usd=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:value<.01?4:2,maximumFractionDigits:value<.01?6:2}).format(value);
export function AiOperationsDashboard(){const[data,setData]=useState<Data|null>(null);const[days,setDays]=useState(30);const[loading,setLoading]=useState(true);const[probing,setProbing]=useState(false);const[message,setMessage]=useState("");
  const load=useCallback(async()=>{setLoading(true);const response=await fetch(`/api/ai/usage?scope=platform&days=${days}`);const payload=await response.json()as Data&{error?:string};if(response.ok)setData(payload);else setMessage(payload.error??"Unable to load AI operations.");setLoading(false);},[days]);useEffect(()=>{void load();},[load]);
  async function probe(){setProbing(true);setMessage("");const response=await fetch("/api/ai/providers?scope=platform",{method:"POST"});const payload=await response.json()as{results?:Array<{provider:string;success:boolean;error?:string}>;error?:string};if(response.ok){const passed=payload.results?.filter(item=>item.success).length??0;setMessage(`Provider probes complete: ${passed}/3 responded successfully.`);await load();}else setMessage(payload.error??"Provider probe failed.");setProbing(false);}
  const maxRequests=Math.max(...(data?.daily.map(item=>item.requests)??[1]),1);const totalProviderRequests=(data?.providerUsage??[]).reduce((sum,item)=>sum+item.requests,0);
  return <main className="min-h-screen bg-[#050913] px-4 py-5 text-frost sm:px-6"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_12%_8%,rgba(168,85,247,.13),transparent_30%),radial-gradient(circle_at_88%_6%,rgba(56,189,248,.14),transparent_28%)]"/><div className="relative mx-auto max-w-[90rem]">
    <nav className="flex flex-col gap-3 rounded-2xl border border-white/10 bg-[#091221]/90 px-4 py-3 backdrop-blur sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="rounded-lg bg-gradient-to-br from-violetGlow to-cyberBlue px-2.5 py-1.5 text-xs font-black">AI</span><div><p className="text-sm font-semibold">AI Operations</p><p className="text-[10px] uppercase tracking-[.18em] text-cyberBlue">Real-provider orchestration</p></div></div><div className="flex flex-wrap gap-4 text-xs text-mist"><Link href="/dashboard/admin">Enterprise</Link><Link href="/dashboard/admin/launch">Launch</Link><Link href="/dashboard/admin/security">Security</Link><Link href="/dashboard">Product</Link></div></nav>
    <header className="flex flex-col gap-5 py-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.28em] text-cyberBlue">Provider control plane</p><h1 className="mt-3 text-4xl font-semibold sm:text-5xl">AI orchestration analytics</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-mist">Requests, real token usage, estimate costs, failover behavior, and provider health across OpenAI, Gemini, and Claude.</p></div><div className="flex gap-2"><select value={days} onChange={event=>setDays(Number(event.target.value))} className="rounded-full border border-white/10 bg-ink px-4 py-2.5 text-xs text-mist"><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select><button onClick={()=>void probe()} disabled={probing} className="rounded-full bg-gradient-to-r from-violetGlow to-cyberBlue px-5 py-2.5 text-xs font-black text-white disabled:opacity-60">{probing?"Probing…":"Run provider probes"}</button></div></header>
    {message?<p role="status" className="mb-4 rounded-2xl border border-cyberBlue/20 bg-cyberBlue/[.06] p-3 text-sm text-mist">{message}</p>:null}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Requests" value={data?.metrics.requests??0} detail={`${days}-day window`}/><Metric label="Tokens" value={(data?.metrics.totalTokens??0).toLocaleString()} detail="input + output"/><Metric label="Cost estimate" value={usd(data?.metrics.costUsd??0)} detail="rate-card estimate"/><Metric label="Error rate" value={`${data?.metrics.errorRate??0}%`} detail="all providers"/><Metric label="Fallback rate" value={`${data?.metrics.fallbackRate??0}%`} detail="requests with failover"/><Metric label="Avg latency" value={`${data?.metrics.averageLatencyMs??0}ms`} detail="end-to-end"/></section>
    <section className="mt-5 grid gap-4 lg:grid-cols-3">{data?.providers.map(provider=><ProviderCard key={provider.provider} provider={provider}/>)??Array.from({length:3},(_,index)=><div key={index} className="h-48 animate-pulse rounded-3xl border border-white/10 bg-white/[.03]"/>)}</section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Request volume</h2><p className="mt-1 text-xs text-mist">Daily routed requests and errors.</p></div><span className="text-xs text-cyberBlue">{loading?"Refreshing…":`${days} days`}</span></div><div className="mt-5 flex h-48 items-end gap-1 overflow-hidden rounded-2xl border border-white/[.07] bg-ink/40 p-4">{data?.daily.map(item=><div key={item.date} title={`${item.date}: ${item.requests} requests`} className="group relative flex h-full flex-1 items-end"><div className="w-full rounded-t bg-gradient-to-t from-violetGlow/70 to-cyberBlue transition group-hover:brightness-125" style={{height:`${Math.max(2,item.requests/maxRequests*100)}%`}}/>{item.errors?<span className="absolute -top-1 right-0 h-1.5 w-1.5 rounded-full bg-rose-300"/>:null}</div>)}</div></div><div className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><h2 className="text-xl font-semibold">Provider distribution</h2><div className="mt-5 space-y-4">{data?.providerUsage.map(item=>{const percent=totalProviderRequests?item.requests/totalProviderRequests*100:0;return <div key={item.provider}><div className="flex justify-between text-xs"><span className="capitalize text-frost">{item.provider}</span><span className="text-mist">{item.requests} · {usd(item.costUsd)}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-gradient-to-r from-violetGlow to-cyberBlue" style={{width:`${percent}%`}}/></div><p className="mt-1 text-[10px] text-mist">{item.tokens.toLocaleString()} tokens · {item.averageLatencyMs}ms avg</p></div>})}</div></div></section>
    <section className="mt-5 overflow-hidden rounded-3xl border border-white/10 bg-white/[.03]"><div className="border-b border-white/10 p-5"><h2 className="text-xl font-semibold">AI response log</h2><p className="mt-1 text-xs text-mist">Request-level provider, model, tokens, cost, latency, and fallback outcomes.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-white/[.035] text-mist"><tr><th className="p-4">Time</th><th className="p-4">Endpoint</th><th className="p-4">Provider</th><th className="p-4">Status</th><th className="p-4">Tokens</th><th className="p-4">Cost</th><th className="p-4">Latency</th><th className="p-4">Fallbacks</th></tr></thead><tbody>{data?.logs.length?data.logs.map(log=><tr key={log.id} className="border-t border-white/[.07]"><td className="p-4 text-mist">{new Date(log.created_at).toLocaleString()}</td><td className="p-4"><span className="block text-frost">{log.endpoint}</span><span className="text-[10px] text-mist">{log.request_type}</span></td><td className="p-4 capitalize text-cyberBlue">{log.provider_used??"none"}<span className="block text-[10px] normal-case text-mist">{log.model??"—"}</span></td><td className="p-4"><Status value={log.status}/>{log.error_message?<span title={log.error_message} className="ml-2 text-rose-300">!</span>:null}</td><td className="p-4">{log.total_tokens.toLocaleString()}</td><td className="p-4">{usd(Number(log.estimated_cost_usd))}</td><td className="p-4">{log.latency_ms}ms</td><td className="p-4">{log.fallback_count}</td></tr>):<tr><td colSpan={8} className="p-10 text-center text-mist">No routed AI requests yet.</td></tr>}</tbody></table></div></section>
  </div></main>;
}
function Metric({label,value,detail}:{label:string;value:string|number;detail:string}){return <article className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className="text-2xl font-semibold">{value}</p><p className="mt-2 text-[10px] font-bold uppercase tracking-[.16em] text-mist">{label}</p><p className="mt-2 text-[10px] text-cyberBlue">{detail}</p></article>}
function ProviderCard({provider}:{provider:Provider}){const healthy=provider.configured&&provider.status==="ready";return <article className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-cyberBlue">{provider.provider}</p><h2 className="mt-2 text-xl font-semibold">{provider.name}</h2></div><span className={`rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase ${healthy?"border-emerald-300/25 text-emerald-200":provider.configured?"border-amber-200/25 text-amber-100":"border-rose-300/25 text-rose-200"}`}>{provider.configured?provider.status:"not configured"}</span></div><p className="mt-4 text-xs text-mist">{provider.defaultModel}</p><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Mini label="Requests" value={provider.totalRequests}/><Mini label="Failures" value={provider.totalFailures}/><Mini label="Latency" value={provider.latencyMs?`${provider.latencyMs}ms`:"—"}/></div>{provider.missing.length?<p className="mt-3 text-[10px] text-rose-200">Missing: {provider.missing.join(", ")}</p>:provider.lastSuccessAt?<p className="mt-3 text-[10px] text-mist">Last success: {new Date(provider.lastSuccessAt).toLocaleString()}</p>:<p className="mt-3 text-[10px] text-mist">Configured; awaiting first request.</p>}</article>}
function Mini({label,value}:{label:string;value:string|number}){return <div className="rounded-xl bg-ink/45 p-2"><p className="text-sm font-semibold">{value}</p><p className="mt-1 text-[9px] uppercase text-mist">{label}</p></div>}
function Status({value}:{value:string}){return <span className={`rounded-full border px-2 py-1 text-[10px] font-bold uppercase ${value==="success"?"border-emerald-300/25 text-emerald-200":"border-rose-300/25 text-rose-200"}`}>{value}</span>}
