"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";

import type { EnterpriseDashboardData, EnterpriseOrganization } from "@/lib/enterprise/types";

const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);
const bytes = (value: number) => value >= 1024 ** 3 ? `${(value / 1024 ** 3).toFixed(1)} GB` : value >= 1024 ** 2 ? `${(value / 1024 ** 2).toFixed(1)} MB` : `${Math.round(value / 1024)} KB`;

export function EnterpriseAdminDashboard({ initialRole }: { initialRole: "super_admin" | "support_admin" }) {
  const [data, setData] = useState<EnterpriseDashboardData | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("all");
  const [tab, setTab] = useState<"agencies" | "audit" | "isolation">("agencies");
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState("");
  const load = useCallback(async () => { setLoading(true); const response = await fetch("/api/enterprise"); const payload = await response.json() as EnterpriseDashboardData & { error?: string }; if (response.ok) setData(payload); else setMessage(payload.error ?? "Unable to load enterprise controls."); setLoading(false); }, []);
  useEffect(() => { void load(); }, [load]);
  const selected = useMemo(() => data?.organizations.find(org => org.id === selectedId) ?? (data?.impersonation ? data.organizations.find(org => org.id === data.impersonation?.organizationId) : null) ?? null, [data, selectedId]);
  const organizations = useMemo(() => (data?.organizations ?? []).filter(org => (status === "all" || org.status === status) && `${org.name} ${org.slug} ${org.ownerEmail}`.toLowerCase().includes(search.toLowerCase())), [data, search, status]);
  async function action(operation: string, organizationId?: string, extra: Record<string, unknown> = {}) { setMessage(""); const response = await fetch("/api/enterprise", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ operation, organizationId, ...extra }) }); const payload = await response.json() as { error?: string }; if (!response.ok) setMessage(payload.error ?? "Action failed."); else { setMessage("Enterprise action completed and audited."); await load(); } }
  const role = data?.role ?? initialRole;
  return <main className="min-h-screen bg-[#050913] px-4 py-5 text-frost sm:px-6"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_12%_10%,rgba(56,189,248,.16),transparent_30%),radial-gradient(circle_at_88%_5%,rgba(168,85,247,.13),transparent_28%)]"/><div className="relative mx-auto max-w-[90rem]">
    <nav className="flex flex-col gap-3 rounded-2xl border border-white/10 bg-[#091221]/90 px-4 py-3 backdrop-blur sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="rounded-lg bg-gradient-to-br from-violetGlow to-cyberBlue px-2.5 py-1.5 text-xs font-black text-white">RM</span><div><p className="text-sm font-semibold">ReelMind Enterprise</p><p className="text-[10px] uppercase tracking-[.18em] text-cyberBlue">Control plane</p></div></div><div className="flex items-center gap-3"><span className="rounded-full border border-cyberBlue/20 bg-cyberBlue/[.06] px-3 py-1 text-xs capitalize text-cyberBlue">{role.replace("_", " ")}</span><Link href="/dashboard/admin/ai" className="text-xs text-mist transition hover:text-frost">AI</Link><Link href="/dashboard/admin/launch" className="text-xs text-mist transition hover:text-frost">Launch</Link><Link href="/dashboard/admin/security" className="text-xs text-mist transition hover:text-frost">Security</Link><Link href="/dashboard" className="text-xs text-mist transition hover:text-frost">Product dashboard</Link></div></nav>
    {data?.impersonation ? <div className="mt-4 flex flex-col gap-3 rounded-2xl border border-amber-300/25 bg-amber-300/[.07] px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-amber-100"><strong>Support lens active:</strong> viewing {data.impersonation.organizationName} in read-only mode until {new Date(data.impersonation.expiresAt).toLocaleTimeString()}.</p><button onClick={() => void action("impersonate_end")} className="rounded-full border border-amber-200/25 px-3 py-1.5 text-xs text-amber-100">Exit lens</button></div> : null}
    <header className="py-8"><p className="text-xs font-bold uppercase tracking-[.28em] text-cyberBlue">Enterprise multi-tenant operations</p><h1 className="mt-3 text-4xl font-semibold sm:text-5xl">Platform command center</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-mist">Monitor recurring revenue, tenant health, capacity, isolation, and privileged support actions across every ReelMind agency.</p></header>
    {message ? <p role="status" className="mb-4 rounded-2xl border border-cyberBlue/20 bg-cyberBlue/[.06] px-4 py-3 text-sm text-mist">{message}</p> : null}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="MRR" value={money(data?.metrics.mrr ?? 0)} detail="active subscriptions"/><Metric label="ARR" value={money(data?.metrics.arr ?? 0)} detail="annualized run rate"/><Metric label="Active agencies" value={data?.metrics.activeAgencies ?? 0} detail={`${data?.organizations.length ?? 0} total tenants`}/><Metric label="Active users" value={data?.metrics.activeUsers ?? 0} detail="unique tenant members"/><Metric label="AI usage" value={data?.metrics.aiUsage ?? 0} detail="stored generations"/><Metric label="Storage" value={bytes(data?.metrics.storageBytes ?? 0)} detail="project assets"/></section>
    <div className="mt-6 flex gap-2 border-b border-white/10">{(["agencies", "audit", "isolation"] as const).map(item => <button key={item} onClick={() => setTab(item)} className={`border-b-2 px-4 py-3 text-xs font-bold uppercase tracking-[.14em] transition ${tab === item ? "border-cyberBlue text-cyberBlue" : "border-transparent text-mist"}`}>{item}</button>)}</div>
    {tab === "agencies" ? <section className="mt-5 grid gap-5 xl:grid-cols-[1fr_25rem]"><div className="overflow-hidden rounded-3xl border border-white/10 bg-white/[.03]"><div className="flex flex-col gap-3 border-b border-white/10 p-4 sm:flex-row"><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search agency, owner, or slug…" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-ink/60 px-4 py-2.5 text-sm outline-none focus:border-cyberBlue/40"/><select value={status} onChange={event => setStatus(event.target.value)} className="rounded-xl border border-white/10 bg-ink/60 px-4 py-2.5 text-sm text-mist"><option value="all">All statuses</option><option value="active">Active</option><option value="suspended">Suspended</option><option value="closed">Closed</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-xs"><thead className="bg-white/[.035] text-mist"><tr><th className="p-4">Agency</th><th className="p-4">Plan</th><th className="p-4">Users</th><th className="p-4">Projects</th><th className="p-4">AI</th><th className="p-4">Storage</th><th className="p-4">Status</th></tr></thead><tbody>{loading ? <tr><td colSpan={7} className="p-10 text-center text-mist">Loading the tenant map…</td></tr> : organizations.map(org => <tr key={org.id} onClick={() => setSelectedId(org.id)} className={`cursor-pointer border-t border-white/[.07] transition hover:bg-cyberBlue/[.04] ${selected?.id === org.id ? "bg-cyberBlue/[.06]" : ""}`}><td className="p-4"><strong className="block text-sm text-frost">{org.name}</strong><span className="mt-1 block text-mist">{org.ownerEmail || org.slug}</span></td><td className="p-4 capitalize text-cyberBlue">{org.plan}<span className="mt-1 block text-[10px] text-mist">{org.subscriptionStatus}</span></td><td className="p-4">{org.members}</td><td className="p-4">{org.projects}</td><td className="p-4">{org.aiGenerations}</td><td className="p-4">{bytes(org.storageBytes)}</td><td className="p-4"><Status value={org.status}/></td></tr>)}</tbody></table></div></div><TenantPanel organization={selected} role={role} onAction={action}/></section> : null}
    {tab === "audit" ? <AuditLog rows={data?.auditLogs ?? []}/> : null}
    {tab === "isolation" ? <Isolation rows={data?.isolation ?? []}/> : null}
  </div></main>;
}

function Metric({ label, value, detail }: { label: string; value: string | number; detail: string }) { return <article className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className="text-2xl font-semibold text-frost">{value}</p><p className="mt-2 text-[10px] font-bold uppercase tracking-[.16em] text-mist">{label}</p><p className="mt-2 text-[10px] text-cyberBlue">{detail}</p></article>; }
function Status({ value }: { value: string }) { const tone = value === "active" ? "border-emerald-300/25 bg-emerald-300/10 text-emerald-200" : value === "suspended" ? "border-rose-300/25 bg-rose-300/10 text-rose-200" : "border-white/10 bg-white/[.04] text-mist"; return <span className={`rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase ${tone}`}>{value}</span>; }
function TenantPanel({ organization, role, onAction }: { organization: EnterpriseOrganization | null; role: string; onAction: (operation: string, organizationId?: string, extra?: Record<string, unknown>) => Promise<void> }) { const [reason, setReason] = useState(""); if (!organization) return <aside className="rounded-3xl border border-dashed border-white/10 p-8 text-center text-sm text-mist">Select an agency to inspect limits and tenant controls.</aside>; return <aside className="h-fit rounded-3xl border border-white/10 bg-white/[.035] p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-cyberBlue">Tenant detail</p><h2 className="mt-2 text-2xl font-semibold">{organization.name}</h2><p className="mt-1 text-xs text-mist">{organization.slug} · created {new Date(organization.createdAt).toLocaleDateString()}</p></div><Status value={organization.status}/></div><div className="mt-5 grid grid-cols-2 gap-2"><Small label="Owner" value={organization.ownerName}/><Small label="MRR" value={money(organization.monthlyRevenue)}/><Small label="Leads" value={`${organization.leads}/${organization.limits.maxLeads}`}/><Small label="Messages" value={`${organization.messages}/${organization.limits.maxMonthlyMessages}`}/></div><button onClick={() => void onAction("impersonate_start", organization.id)} className="mt-4 w-full rounded-full border border-cyberBlue/30 py-2.5 text-xs font-bold text-cyberBlue transition hover:bg-cyberBlue hover:text-ink">Open read-only support lens</button>{role === "super_admin" ? <div className="mt-5 border-t border-white/10 pt-5"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-mist">Suspension control</p>{organization.status === "active" ? <form onSubmit={(event: FormEvent) => { event.preventDefault(); void onAction("suspend", organization.id, { reason }); }}><textarea value={reason} onChange={event => setReason(event.target.value)} required rows={3} placeholder="Required operational reason…" className="mt-3 w-full resize-none rounded-xl border border-white/10 bg-ink/60 p-3 text-xs outline-none focus:border-rose-300/30"/><button className="mt-2 w-full rounded-full border border-rose-300/25 py-2.5 text-xs font-bold text-rose-200">Suspend agency</button></form> : <button onClick={() => void onAction("resume", organization.id, { reason: "Restored by Super Admin" })} className="mt-3 w-full rounded-full border border-emerald-300/25 py-2.5 text-xs font-bold text-emerald-200">Resume agency</button>}</div> : <p className="mt-5 rounded-xl border border-white/10 p-3 text-xs text-mist">Support Admins have read-only tenant access. Suspension and limit changes require a Super Admin.</p>}</aside>; }
function Small({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-ink/45 p-3"><p className="truncate text-sm font-semibold">{value}</p><p className="mt-1 text-[10px] uppercase text-mist">{label}</p></div>; }
function AuditLog({ rows }: { rows: EnterpriseDashboardData["auditLogs"] }) { return <section className="mt-5 rounded-3xl border border-white/10 bg-white/[.03] p-5"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Enterprise audit trail</h2><p className="mt-1 text-sm text-mist">Privileged actions are immutable and actor-attributed.</p></div><span className="text-xs text-cyberBlue">{rows.length} recent events</span></div><div className="mt-5 space-y-2">{rows.length ? rows.map(row => <article key={row.id} className="flex flex-col gap-2 rounded-2xl border border-white/[.07] bg-ink/45 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium capitalize">{row.action.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-mist">{row.reason || `Tenant ${row.organization_id?.slice(0, 8) ?? "platform"}`}</p></div><div className="text-right"><p className="text-[10px] uppercase text-cyberBlue">{row.actor_role?.replace("_", " ")}</p><p className="mt-1 text-[10px] text-mist">{new Date(row.created_at).toLocaleString()}</p></div></article>) : <p className="text-sm text-mist">No privileged actions recorded yet.</p>}</div></section>; }
function Isolation({ rows }: { rows: EnterpriseDashboardData["isolation"] }) { const verified = rows.length > 0 && rows.every(row => row.verified); return <section className="mt-5 rounded-3xl border border-white/10 bg-white/[.03] p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-semibold">Tenant isolation verification</h2><p className="mt-1 text-sm text-mist">Schema-level check for organization scope and row-level security.</p></div><span className={`w-fit rounded-full border px-3 py-1.5 text-xs font-bold ${verified ? "border-emerald-300/25 bg-emerald-300/10 text-emerald-200" : "border-amber-300/25 bg-amber-300/10 text-amber-100"}`}>{verified ? "All checks verified" : "Review required"}</span></div><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{rows.map(row => <article key={row.table_name} className="rounded-xl border border-white/[.07] bg-ink/45 p-3"><div className="flex items-center justify-between gap-2"><code className="text-xs text-frost">{row.table_name}</code><span className={row.verified ? "text-emerald-300" : "text-rose-300"}>{row.verified ? "✓" : "!"}</span></div><p className="mt-2 text-[10px] text-mist">RLS {row.rls_enabled ? "on" : "off"} · tenant key {row.organization_scoped ? "present" : "missing"}</p></article>)}</div></section>; }
