"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";

import type { LaunchReadiness, LaunchReport, ReadinessCheck, ReadinessStatus } from "@/lib/launch-readiness/types";

type Payload = { readiness: LaunchReadiness; reports: LaunchReport[] };
const serviceLabels: Record<string, string> = { supabase: "Supabase", resend: "Resend", razorpay: "Razorpay", whatsapp: "WhatsApp", openai: "OpenAI", gemini: "Gemini", claude: "Claude", mobile: "Mobile", storage: "Storage" };
export function LaunchReadinessDashboard() {
  const [data, setData] = useState<Payload | null>(null); const [loading, setLoading] = useState(true); const [generating, setGenerating] = useState(false); const [message, setMessage] = useState(""); const [tab, setTab] = useState<"checklist" | "environment" | "report">("checklist");
  const load = useCallback(async () => { setLoading(true); const response = await fetch("/api/launch-readiness"); const payload = await response.json() as Payload & { error?: string }; if (response.ok) setData(payload); else setMessage(payload.error ?? "Unable to evaluate launch readiness."); setLoading(false); }, []); useEffect(() => { void load(); }, [load]);
  async function generateReport() { setGenerating(true); setMessage(""); const response = await fetch("/api/launch-readiness", { method: "POST" }); const payload = await response.json() as { readiness?: LaunchReadiness; report?: LaunchReport; error?: string }; if (response.ok && payload.readiness && payload.report) { setData(current => ({ readiness: payload.readiness!, reports: [payload.report!, ...(current?.reports ?? [])] })); setTab("report"); setMessage("Production go-live report generated and audit logged."); } else setMessage(payload.error ?? "Report generation failed."); setGenerating(false); }
  function downloadReport() { if (!data) return; const latest = data.reports[0]; const blob = new Blob([JSON.stringify({ reportId: latest?.id ?? null, product: "ReelMind AI", ...data.readiness }, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `reelmind-go-live-${data.readiness.generatedAt.slice(0,10)}.json`; link.click(); URL.revokeObjectURL(url); }
  const readiness = data?.readiness; const categories = useMemo(() => { const map = new Map<string, ReadinessCheck[]>(); (readiness?.checks ?? []).forEach(item => map.set(item.category, [...(map.get(item.category) ?? []), item])); return [...map.entries()]; }, [readiness]);
  return <main className="min-h-screen bg-[#050913] px-4 py-5 text-frost sm:px-6 print:bg-white print:text-black"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_12%_8%,rgba(34,197,94,.11),transparent_28%),radial-gradient(circle_at_86%_5%,rgba(56,189,248,.14),transparent_30%)] print:hidden"/><div className="relative mx-auto max-w-[90rem]">
    <nav className="flex flex-col gap-3 rounded-2xl border border-white/10 bg-[#091221]/90 px-4 py-3 backdrop-blur sm:flex-row sm:items-center sm:justify-between print:hidden"><div className="flex items-center gap-3"><span className="rounded-lg bg-gradient-to-br from-emerald-400 to-cyberBlue px-2.5 py-1.5 text-xs font-black text-ink">GO</span><div><p className="text-sm font-semibold">ReelMind Launch Control</p><p className="text-[10px] uppercase tracking-[.18em] text-cyberBlue">Production readiness</p></div></div><div className="flex gap-4 text-xs text-mist"><Link href="/dashboard/admin">Enterprise</Link><Link href="/dashboard/admin/ai">AI</Link><Link href="/dashboard/admin/security">Security</Link><Link href="/dashboard">Product</Link></div></nav>
    <header className="flex flex-col gap-5 py-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.28em] text-cyberBlue">Phase 25 · launch readiness</p><h1 className="mt-3 text-4xl font-semibold sm:text-5xl">Production go-live gate</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-mist print:text-slate-600">A weighted, evidence-based view of configuration, integrations, infrastructure, and operations.</p></div><div className="flex flex-wrap gap-2 print:hidden"><button onClick={() => void load()} disabled={loading} className="rounded-full border border-white/10 px-4 py-2.5 text-xs font-bold">{loading ? "Checking…" : "Run checks"}</button><button onClick={() => void generateReport()} disabled={generating} className="rounded-full bg-gradient-to-r from-emerald-400 to-cyberBlue px-5 py-2.5 text-xs font-black text-ink">{generating ? "Generating…" : "Generate go-live report"}</button></div></header>
    {message ? <p role="status" className="mb-4 rounded-2xl border border-cyberBlue/20 bg-cyberBlue/[.06] p-3 text-sm text-mist print:hidden">{message}</p> : null}
    <section className="grid gap-5 xl:grid-cols-[22rem_1fr]"><ScoreCard readiness={readiness}/><div className="grid gap-3 sm:grid-cols-3"><Summary label="Ready checks" value={readiness?.summary.ready ?? 0} tone="emerald"/><Summary label="Warnings" value={readiness?.summary.warning ?? 0} tone="amber"/><Summary label="Launch blockers" value={readiness?.summary.blocked ?? 0} tone="rose"/><div className="sm:col-span-3 grid gap-3 sm:grid-cols-3 lg:grid-cols-5">{Object.entries(serviceLabels).map(([id,label]) => <Service key={id} label={label} status={readiness?.services[id] ?? "warning"}/>)}</div></div></section>
    <div className="mt-6 flex gap-2 border-b border-white/10 print:hidden">{(["checklist","environment","report"] as const).map(item => <button key={item} onClick={() => setTab(item)} className={`border-b-2 px-4 py-3 text-xs font-bold uppercase tracking-[.14em] ${tab === item ? "border-cyberBlue text-cyberBlue" : "border-transparent text-mist"}`}>{item}</button>)}</div>
    {tab === "checklist" ? <div className="mt-5 space-y-5">{categories.map(([category,items]) => <section key={category} className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">{category}</h2><span className="text-xs text-mist">{items.reduce((sum,item)=>sum+item.points,0)}/{items.reduce((sum,item)=>sum+item.weight,0)} points</span></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{items.map(item => <CheckCard key={item.id} item={item}/>)}</div></section>)}</div> : null}
    {tab === "environment" ? <Environment readiness={readiness}/> : null}
    {tab === "report" ? <Report readiness={readiness} reports={data?.reports ?? []} onDownload={downloadReport}/> : null}
  </div></main>;
}
function ScoreCard({ readiness }: { readiness?: LaunchReadiness }) { const score = readiness?.score ?? 0; const color = readiness?.verdict === "production_ready" ? "#34d399" : readiness?.verdict === "conditional" ? "#fbbf24" : "#fb7185"; return <article className="rounded-3xl border border-white/10 bg-white/[.035] p-6 text-center"><div className="mx-auto grid h-44 w-44 place-items-center rounded-full" style={{ background: `conic-gradient(${color} ${score * 3.6}deg, rgba(255,255,255,.08) 0)` }}><div className="grid h-36 w-36 place-items-center rounded-full bg-[#07101d]"><div><p className="text-5xl font-semibold">{score}</p><p className="text-xs text-mist">out of 100</p></div></div></div><p className="mt-5 text-xs font-bold uppercase tracking-[.2em]" style={{ color }}>{readiness?.verdict.replaceAll("_", " ") ?? "evaluating"}</p><p className="mt-2 text-xs text-mist">Evaluated {readiness ? new Date(readiness.generatedAt).toLocaleString() : "now"}</p></article>; }
function Summary({ label,value,tone }: { label:string;value:number;tone:"emerald"|"amber"|"rose" }) { const colors={emerald:"text-emerald-300",amber:"text-amber-200",rose:"text-rose-300"};return <article className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className={`text-3xl font-semibold ${colors[tone]}`}>{value}</p><p className="mt-2 text-[10px] font-bold uppercase tracking-[.16em] text-mist">{label}</p></article>; }
function Service({ label,status }: { label:string;status:ReadinessStatus }) { const tone=status==="ready"?"border-emerald-300/20 text-emerald-200":status==="warning"?"border-amber-200/20 text-amber-100":"border-rose-300/20 text-rose-200";return <article className={`rounded-xl border bg-white/[.025] p-3 ${tone}`}><div className="flex items-center justify-between"><strong className="text-xs text-frost">{label}</strong><span className="text-xs">{status==="ready"?"✓":status==="warning"?"•":"!"}</span></div><p className="mt-2 text-[9px] font-bold uppercase">{status}</p></article>; }
function CheckCard({ item }: { item:ReadinessCheck }) { return <article className="rounded-2xl border border-white/[.08] bg-ink/45 p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><ServiceDot status={item.status}/><h3 className="text-sm font-semibold">{item.name}</h3></div><p className="mt-2 text-xs leading-5 text-mist">{item.summary}</p></div><span className="shrink-0 text-xs text-cyberBlue">{item.points}/{item.weight}</span></div>{item.details.length ? <ul className="mt-3 space-y-1 text-[10px] text-mist">{item.details.map(detail=><li key={detail}>· {detail}</li>)}</ul>:null}{item.action?<p className="mt-3 rounded-lg bg-white/[.035] p-2 text-[10px] text-amber-100">Next: {item.action}</p>:null}</article>; }
function ServiceDot({status}:{status:ReadinessStatus}){return <span className={`h-2 w-2 rounded-full ${status==="ready"?"bg-emerald-300":status==="warning"?"bg-amber-200":"bg-rose-300"}`}/>;}
function Environment({readiness}:{readiness?:LaunchReadiness}){const missing=readiness?.missingConfiguration??[];return <section className="mt-5 grid gap-5 lg:grid-cols-[1fr_.7fr]"><div className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><h2 className="text-xl font-semibold">Missing configuration detection</h2><p className="mt-2 text-sm text-mist">Only variable names are shown. Secret values never leave the server.</p><div className="mt-5 grid gap-2 sm:grid-cols-2">{missing.length?missing.map(name=><code key={name} className="rounded-xl border border-amber-200/15 bg-amber-200/[.05] p-3 text-xs text-amber-100">{name}</code>):<p className="text-sm text-emerald-200">No missing configuration detected.</p>}</div></div><div className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><h2 className="text-xl font-semibold">Configuration rules</h2><ul className="mt-4 space-y-3 text-xs leading-5 text-mist"><li>· Production secrets must differ from preview and development.</li><li>· OAuth callback URLs must use the canonical HTTPS origin.</li><li>· Mobile Expo variables belong in the EAS environment as well as launch validation.</li><li>· Provider keys are optional only when local fallback behavior is acceptable.</li><li>· Run checks again after every environment or migration change.</li></ul></div></section>}
function Report({readiness,reports,onDownload}:{readiness?:LaunchReadiness;reports:LaunchReport[];onDownload:()=>void}){return <section className="mt-5 grid gap-5 lg:grid-cols-[1fr_.7fr]"><article className="rounded-3xl border border-white/10 bg-white/[.03] p-6 print:border-slate-200"><p className="text-xs font-bold uppercase tracking-[.22em] text-cyberBlue">Production go-live report</p><h2 className="mt-3 text-3xl font-semibold">ReelMind AI · {readiness?.verdict.replaceAll("_"," ")}</h2><p className="mt-3 text-sm text-mist print:text-slate-600">Launch score: {readiness?.score ?? 0}/100 · {readiness?.summary.ready ?? 0} ready · {readiness?.summary.warning ?? 0} warnings · {readiness?.summary.blocked ?? 0} blockers</p><div className="mt-6 space-y-3">{readiness?.checks.map(item=><div key={item.id} className="flex items-start justify-between gap-4 border-b border-white/[.07] pb-3 print:border-slate-200"><div><strong className="text-sm">{item.name}</strong><p className="mt-1 text-xs text-mist print:text-slate-600">{item.summary}</p></div><span className="text-xs uppercase">{item.status}</span></div>)}</div><div className="mt-6 flex gap-2 print:hidden"><button onClick={onDownload} className="rounded-full bg-cyberBlue px-4 py-2 text-xs font-bold text-ink">Download JSON</button><button onClick={()=>window.print()} className="rounded-full border border-white/10 px-4 py-2 text-xs">Print report</button></div></article><aside className="rounded-3xl border border-white/10 bg-white/[.03] p-5 print:hidden"><h2 className="text-xl font-semibold">Report history</h2><div className="mt-4 space-y-2">{reports.length?reports.map(report=><article key={report.id} className="rounded-xl bg-ink/45 p-3"><div className="flex items-center justify-between"><strong className="text-sm">{report.score}/100</strong><span className="text-[10px] uppercase text-cyberBlue">{report.verdict.replaceAll("_"," ")}</span></div><p className="mt-2 text-[10px] text-mist">{new Date(report.generated_at).toLocaleString()} · {report.missing_configuration.length} missing settings</p></article>):<p className="text-sm text-mist">Generate the first signed-off report.</p>}</div></aside></section>}
