"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";

type EventRow = { id: string; event_type: string; severity: string; source: string; route: string | null; message: string | null; metadata: Record<string, unknown>; resolved_at: string | null; created_at: string };
type Queue = { name: string; pending: number; processing: number; failed: number; oldest: string | null };
type Cron = { id: string; name: string; expected_interval_minutes: number; effectiveStatus: string; last_completed_at: string | null; last_duration_ms: number | null; last_error: string | null; consecutive_failures: number };
type Data = { role: string; metrics: { errors: number; failedJobs: number; rateLimits: number; abuseAttempts: number }; events: EventRow[]; queues: Queue[]; crons: Cron[]; integrations: { sentry: boolean; distributedRateLimit: boolean; healthToken: boolean; cronSecret: boolean; backups: string } };

export function SecurityOperationsDashboard() {
  const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [filter, setFilter] = useState("all");
  const load = useCallback(async () => { setLoading(true); const response = await fetch("/api/security"); const payload = await response.json() as Data & { error?: string }; if (response.ok) setData(payload); else setMessage(payload.error ?? "Unable to load security telemetry."); setLoading(false); }, []);
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 60000); return () => window.clearInterval(timer); }, [load]);
  const events = useMemo(() => (data?.events ?? []).filter(row => filter === "all" || row.event_type === filter), [data, filter]);
  const days = useMemo(() => Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setDate(date.getDate() - (6 - index)); const key = date.toISOString().slice(0, 10); return { key, label: date.toLocaleDateString(undefined, { weekday: "short" }), count: (data?.events ?? []).filter(row => row.created_at.startsWith(key)).length }; }), [data]); const maxDay = Math.max(...days.map(day => day.count), 1);
  return <main className="min-h-screen bg-[#050913] px-4 py-5 text-frost sm:px-6"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_15%_8%,rgba(244,63,94,.09),transparent_28%),radial-gradient(circle_at_85%_5%,rgba(56,189,248,.14),transparent_30%)]"/><div className="relative mx-auto max-w-[90rem]">
    <nav className="flex flex-col gap-3 rounded-2xl border border-white/10 bg-[#091221]/90 px-4 py-3 backdrop-blur sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="rounded-lg bg-gradient-to-br from-rose-500 to-cyberBlue px-2.5 py-1.5 text-xs font-black">SH</span><div><p className="text-sm font-semibold">Security Operations</p><p className="text-[10px] uppercase tracking-[.18em] text-cyberBlue">Production hardening</p></div></div><div className="flex gap-4 text-xs text-mist"><Link href="/dashboard/admin" className="hover:text-frost">Enterprise</Link><Link href="/dashboard/admin/ai" className="hover:text-frost">AI</Link><Link href="/dashboard/admin/launch" className="hover:text-frost">Launch</Link><a href="/api/health" target="_blank" rel="noreferrer" className="hover:text-frost">Health API</a><Link href="/dashboard" className="hover:text-frost">Product</Link></div></nav>
    <header className="flex flex-col gap-4 py-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.28em] text-cyberBlue">Platform defense & reliability</p><h1 className="mt-3 text-4xl font-semibold sm:text-5xl">Security command center</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-mist">Live ingress protection, application errors, background queues, scheduled jobs, and recovery posture.</p></div><button onClick={() => void load()} disabled={loading} className="rounded-full border border-cyberBlue/30 px-4 py-2 text-xs font-bold text-cyberBlue">{loading ? "Refreshing…" : "Refresh telemetry"}</button></header>
    {message ? <p className="mb-4 rounded-2xl border border-rose-300/20 bg-rose-300/[.06] p-3 text-sm text-rose-100">{message}</p> : null}
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Errors" value={data?.metrics.errors ?? 0} detail="last 24 hours" tone="rose"/><Metric label="Failed jobs" value={data?.metrics.failedJobs ?? 0} detail="across active queues" tone="amber"/><Metric label="Rate limits" value={data?.metrics.rateLimits ?? 0} detail="requests throttled" tone="blue"/><Metric label="Abuse attempts" value={data?.metrics.abuseAttempts ?? 0} detail="bots and rejected API calls" tone="violet"/></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Security events</h2><p className="mt-1 text-xs text-mist">Seven-day ingress and application signal.</p></div><select value={filter} onChange={event => setFilter(event.target.value)} className="rounded-full border border-white/10 bg-ink px-3 py-2 text-xs text-mist"><option value="all">All events</option><option value="error">Errors</option><option value="rate_limit">Rate limits</option><option value="bot_blocked">Bots</option><option value="api_rejected">API rejects</option></select></div><div className="mt-5 flex h-32 items-end gap-3 rounded-2xl border border-white/[.07] bg-ink/40 p-4">{days.map(day => <div key={day.key} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><span className="text-[10px] text-mist">{day.count}</span><div className="w-full rounded-t bg-gradient-to-t from-violetGlow/70 to-cyberBlue" style={{ height: `${Math.max(4, day.count / maxDay * 80)}%` }}/><span className="text-[10px] text-mist">{day.label}</span></div>)}</div><div className="mt-4 max-h-[32rem] space-y-2 overflow-y-auto pr-1">{events.length ? events.slice(0, 100).map(row => <article key={row.id} className="flex flex-col gap-2 rounded-xl border border-white/[.07] bg-ink/45 p-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex items-center gap-2"><Severity value={row.severity}/><span className="text-[10px] font-bold uppercase text-cyberBlue">{row.event_type.replaceAll("_", " ")}</span></div><p className="mt-2 truncate text-xs text-frost">{row.message || "Security event"}</p><p className="mt-1 truncate text-[10px] text-mist">{row.source}{row.route ? ` · ${row.route}` : ""}</p></div><time className="shrink-0 text-[10px] text-mist">{new Date(row.created_at).toLocaleString()}</time></article>) : <p className="py-10 text-center text-sm text-mist">No matching security events. Quiet is rather lovely.</p>}</div></div><Integrations data={data?.integrations}/></section>
    <section className="mt-5 grid gap-5 lg:grid-cols-2"><QueuePanel rows={data?.queues ?? []}/><CronPanel rows={data?.crons ?? []}/></section>
    <section className="mt-5 rounded-3xl border border-white/10 bg-white/[.03] p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-cyberBlue">Backup & recovery</p><h2 className="mt-2 text-xl font-semibold">Production recovery runbook</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-mist">Daily database backups, point-in-time recovery where supported, monthly restore drills, storage inventory exports, and encrypted off-site configuration escrow are documented for operations.</p></div><code className="rounded-full border border-white/10 px-4 py-2 text-xs text-frost">docs/production-backup-strategy.md</code></div></section>
  </div></main>;
}
function Metric({ label, value, detail, tone }: { label: string; value: number; detail: string; tone: "rose" | "amber" | "blue" | "violet" }) { const colors = { rose: "text-rose-300", amber: "text-amber-200", blue: "text-cyberBlue", violet: "text-violetGlow" }; return <article className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className={`text-3xl font-semibold ${colors[tone]}`}>{value}</p><p className="mt-2 text-[10px] font-bold uppercase tracking-[.16em] text-frost">{label}</p><p className="mt-2 text-xs text-mist">{detail}</p></article>; }
function Severity({ value }: { value: string }) { const color = value === "critical" ? "bg-rose-400" : value === "error" ? "bg-orange-300" : value === "warning" ? "bg-amber-200" : "bg-cyberBlue"; return <span className={`h-2 w-2 rounded-full ${color}`}/>; }
function Integrations({ data }: { data: Data["integrations"] | undefined }) { const rows = [{ label: "Sentry error transport", enabled: data?.sentry }, { label: "Distributed rate limiting", enabled: data?.distributedRateLimit }, { label: "Protected health detail", enabled: data?.healthToken }, { label: "Authenticated cron jobs", enabled: data?.cronSecret }, { label: "Backup runbook", enabled: data?.backups === "runbook_ready" }]; return <aside className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><h2 className="text-xl font-semibold">Production controls</h2><p className="mt-1 text-xs text-mist">Configuration readiness—not secret values.</p><div className="mt-5 space-y-3">{rows.map(row => <div key={row.label} className="flex items-center justify-between rounded-xl bg-ink/45 p-3"><span className="text-sm text-mist">{row.label}</span><span className={`rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase ${row.enabled ? "border-emerald-300/25 bg-emerald-300/10 text-emerald-200" : "border-amber-200/25 bg-amber-200/10 text-amber-100"}`}>{row.enabled ? "enabled" : "configure"}</span></div>)}</div></aside>; }
function QueuePanel({ rows }: { rows: Queue[] }) { return <section className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><h2 className="text-xl font-semibold">Queue monitoring</h2><p className="mt-1 text-xs text-mist">Workflow, AI-agent, and publishing backlog.</p><div className="mt-5 space-y-3">{rows.map(row => <article key={row.name} className="rounded-xl border border-white/[.07] bg-ink/45 p-4"><div className="flex items-center justify-between"><strong className="text-sm capitalize">{row.name.replace("-", " ")}</strong><span className={row.failed ? "text-xs text-rose-300" : "text-xs text-emerald-200"}>{row.failed ? `${row.failed} failed` : "healthy"}</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-center"><Small label="Pending" value={row.pending}/><Small label="Processing" value={row.processing}/><Small label="Failed" value={row.failed}/></div>{row.oldest ? <p className="mt-3 text-[10px] text-mist">Oldest pending: {new Date(row.oldest).toLocaleString()}</p> : null}</article>)}</div></section>; }
function CronPanel({ rows }: { rows: Cron[] }) { return <section className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><h2 className="text-xl font-semibold">Cron monitoring</h2><p className="mt-1 text-xs text-mist">Heartbeat, duration, and consecutive failures.</p><div className="mt-5 space-y-3">{rows.map(row => <article key={row.id} className="rounded-xl border border-white/[.07] bg-ink/45 p-4"><div className="flex items-center justify-between gap-3"><strong className="text-sm">{row.name}</strong><span className={`rounded-full border px-2 py-1 text-[10px] font-bold uppercase ${row.effectiveStatus === "healthy" ? "border-emerald-300/25 text-emerald-200" : row.effectiveStatus === "running" ? "border-cyberBlue/25 text-cyberBlue" : "border-rose-300/25 text-rose-200"}`}>{row.effectiveStatus}</span></div><p className="mt-2 text-xs text-mist">Every {row.expected_interval_minutes}m · {row.last_duration_ms ?? 0}ms · {row.consecutive_failures} consecutive failures</p>{row.last_error ? <p className="mt-2 text-xs text-rose-200">{row.last_error}</p> : null}</article>)}</div></section>; }
function Small({ label, value }: { label: string; value: number }) { return <div className="rounded-lg bg-white/[.035] p-2"><p className="text-lg font-semibold">{value}</p><p className="text-[9px] uppercase text-mist">{label}</p></div>; }
