import { NextResponse } from "next/server";
import { answerCopilot, buildAgencySnapshot, ensureAiAgents, generateAiAgencyInsights } from "@/lib/ai-agency/engine";
import { createAdminClient } from "@/lib/supabase/admin";
import { permissionError, resolvePermission } from "@/lib/team/permission-guards";

async function loadData(organizationId:string) {
  const admin=createAdminClient();const [agents,snapshot,recommendations,tasks]=await Promise.all([ensureAiAgents(organizationId),buildAgencySnapshot(organizationId),admin.from("ai_recommendations").select("id,agent_id,project_id,lead_id,recommendation_type,title,recommendation,score,severity,status,metadata,created_at").eq("organization_id",organizationId).eq("status","open").order("created_at",{ascending:false}).limit(100),admin.from("ai_tasks").select("id,agent_id,project_id,lead_id,title,description,priority,status,metadata,created_at").eq("organization_id",organizationId).in("status",["suggested","accepted"]).order("created_at",{ascending:false}).limit(100)]);return{agents,snapshot,recommendations:recommendations.data??[],tasks:tasks.data??[]};
}

export async function GET(request:Request){const organizationId=new URL(request.url).searchParams.get("organizationId");const access=await resolvePermission("analytics:view",organizationId);if(!access.ok)return permissionError(access);let data=await loadData(access.organizationId);if(!data.agents.some(agent=>agent.last_run_at)){await generateAiAgencyInsights(access.organizationId,access.user.id);data=await loadData(access.organizationId);}return NextResponse.json(data);}

export async function POST(request:Request){const body=await request.json().catch(()=>({})) as Record<string,unknown>;const organizationId=typeof body.organizationId==="string"?body.organizationId:"";const access=await resolvePermission("analytics:view",organizationId);if(!access.ok)return permissionError(access);const operation=typeof body.operation==="string"?body.operation:"generate";const admin=createAdminClient();
  if(operation==="generate"){await generateAiAgencyInsights(access.organizationId,access.user.id);return NextResponse.json(await loadData(access.organizationId));}
  if(operation==="ask"){const question=typeof body.question==="string"?body.question.trim().slice(0,500):"";if(!question)return NextResponse.json({error:"Ask the copilot a question."},{status:400});const snapshot=await buildAgencySnapshot(access.organizationId);const answer=answerCopilot(question,snapshot);await admin.from("team_activity_logs").insert({organization_id:access.organizationId,user_id:access.user.id,action:"ai_copilot_asked",metadata:{question,answer}});return NextResponse.json({answer});}
  if(operation==="task_status"){const id=typeof body.id==="string"?body.id:"";const status=body.status;if(!id||!["accepted","completed","dismissed"].includes(String(status)))return NextResponse.json({error:"Invalid task update."},{status:400});const{error}=await admin.from("ai_tasks").update({status,updated_at:new Date().toISOString()}).eq("id",id).eq("organization_id",access.organizationId);if(error)return NextResponse.json({error:error.message},{status:400});await admin.from("team_activity_logs").insert({organization_id:access.organizationId,user_id:access.user.id,action:"ai_task_updated",metadata:{taskId:id,status}});return NextResponse.json({success:true});}
  if(operation==="recommendation_status"){const id=typeof body.id==="string"?body.id:"";const status=body.status;if(!id||!["accepted","dismissed"].includes(String(status)))return NextResponse.json({error:"Invalid recommendation update."},{status:400});const{error}=await admin.from("ai_recommendations").update({status}).eq("id",id).eq("organization_id",access.organizationId);if(error)return NextResponse.json({error:error.message},{status:400});await admin.from("team_activity_logs").insert({organization_id:access.organizationId,user_id:access.user.id,action:"ai_recommendation_updated",metadata:{recommendationId:id,status}});return NextResponse.json({success:true});}
  return NextResponse.json({error:"Unsupported operation."},{status:400});
}
