import "server-only";

import { estimateTokens } from "@/lib/providers/provider-client-utils";
import { executeProvider, getProvider } from "@/lib/providers/provider-registry";
import type { TextProviderData } from "@/lib/providers/provider-types";
import { createAdminClient } from "@/lib/supabase/admin";
import type { AiAttempt, AiRouterInput, AiRouterResult, AiTextProvider } from "@/lib/ai-router/types";

const supported = ["openai","gemini","claude"] as const;
const modelFor = (provider: AiTextProvider, requested?: string) => requested || (provider === "openai" ? process.env.OPENAI_TEXT_MODEL : provider === "gemini" ? process.env.GEMINI_TEXT_MODEL : process.env.CLAUDE_TEXT_MODEL) || getProvider(provider)?.definition.defaultModel || "";
function providerOrder() { const configured = (process.env.AI_PROVIDER_ORDER ?? "openai,gemini,claude").split(",").map(item => item.trim()).filter((item): item is AiTextProvider => (supported as readonly string[]).includes(item)); return [...new Set([...configured, ...supported])] as AiTextProvider[]; }
function candidates(requested: AiRouterInput["provider"], fallback: boolean) { const order = providerOrder(); if (!requested || requested === "auto") return order; return fallback ? [requested, ...order.filter(item => item !== requested)] : [requested]; }

async function pricing(provider: AiTextProvider, model: string) { const admin = createAdminClient(); const { data: exact } = await admin.from("ai_provider_pricing").select("input_usd_per_million,output_usd_per_million").eq("provider", provider).eq("model", model).eq("is_active", true).order("effective_from", { ascending: false }).limit(1).maybeSingle(); if (exact) return exact; const { data } = await admin.from("ai_provider_pricing").select("input_usd_per_million,output_usd_per_million").eq("provider", provider).eq("is_active", true).order("effective_from", { ascending: false }).limit(1).maybeSingle(); return data ?? { input_usd_per_million: 0, output_usd_per_million: 0 }; }
async function updateHealth(provider: AiTextProvider, input: { success: boolean; model: string; latencyMs: number; error?: string }) { try { const admin = createAdminClient(); const { data: current } = await admin.from("ai_provider_health_checks").select("total_requests,total_failures,consecutive_failures").eq("provider", provider).maybeSingle(); const now = new Date().toISOString(); await admin.from("ai_provider_health_checks").upsert({ provider, status: input.success ? "ready" : Number(current?.consecutive_failures ?? 0) + 1 >= 3 ? "down" : "degraded", model: input.model, last_checked_at: now, last_success_at: input.success ? now : undefined, last_failure_at: input.success ? undefined : now, last_latency_ms: input.latencyMs, consecutive_failures: input.success ? 0 : Number(current?.consecutive_failures ?? 0) + 1, last_error: input.success ? null : input.error?.slice(0,1000), total_requests: Number(current?.total_requests ?? 0) + 1, total_failures: Number(current?.total_failures ?? 0) + (input.success ? 0 : 1), updated_at: now }, { onConflict: "provider" }); } catch { /* Telemetry cannot break provider delivery. */ } }
async function logRequest(input: AiRouterInput, log: Record<string, unknown>) { try { await createAdminClient().from("ai_request_logs").insert({ organization_id: input.organizationId ?? null, user_id: input.userId ?? null, endpoint: input.endpoint, request_type: input.requestType, prompt_template_key: input.promptTemplateKey ?? null, requested_provider: input.provider ?? "auto", prompt_text: input.prompt.slice(0,50000), metadata: input.metadata ?? {}, ...log }); } catch (error) { console.error("[ai-router] request logging failed", error); } }

export async function routeAiText(input: AiRouterInput): Promise<AiRouterResult> {
  const requestId = crypto.randomUUID(); const started = Date.now(); const attempts: AiAttempt[] = []; const order = candidates(input.provider, input.allowFallback !== false); let lastError = "No configured AI provider is available.";
  for (const provider of order) {
    const model = modelFor(provider, provider === input.provider ? input.model : undefined); const definition = getProvider(provider); const health = definition?.health();
    if (!definition || health?.status !== "ready") { const error = `Missing ${health?.missing.join(", ") || "provider configuration"}.`; attempts.push({ provider, model, status: "skipped", latencyMs: 0, error }); lastError = error; continue; }
    const attemptStarted = Date.now();
    try { const result = await executeProvider({ provider, capability: "text", payload: { prompt: input.prompt, system: input.system, model }, mockSafe: false, timeoutMs: Number(process.env.AI_PROVIDER_TIMEOUT_MS ?? 45000) }); const latency = Date.now() - attemptStarted; const data = result?.data as TextProviderData | undefined; if (!result?.success || result.mocked || !data?.text?.trim()) throw new Error(result?.error || `${provider} returned no real response.`); const inputTokens = result.usage.inputTokens ?? estimateTokens([input.system,input.prompt].filter(Boolean).join("\n\n")); const outputTokens = result.usage.outputTokens ?? Math.max(1, result.usage.tokens - inputTokens, estimateTokens(data.text)); const totalTokens = inputTokens + outputTokens; const rate = await pricing(provider, data.model || model); const estimatedCostUsd = Number(((inputTokens * Number(rate.input_usd_per_million) + outputTokens * Number(rate.output_usd_per_million)) / 1_000_000).toFixed(6)); attempts.push({ provider, model: data.model || model, status: "success", latencyMs: latency }); await updateHealth(provider,{success:true,model:data.model||model,latencyMs:latency}); const fallbackCount = Math.max(0, attempts.filter(attempt => attempt.status !== "success").length); const response: AiRouterResult = { requestId, text: data.text.trim(), provider, model: data.model || model, usage: { inputTokens, outputTokens, totalTokens, estimatedCostUsd, latencyMs: Date.now()-started, fallbackCount }, attempts }; await logRequest(input,{ request_id:requestId,provider_used:provider,model:response.model,status:"success",fallback_count:fallbackCount,input_tokens:inputTokens,output_tokens:outputTokens,total_tokens:totalTokens,estimated_cost_usd:estimatedCostUsd,latency_ms:response.usage.latencyMs,response_text:response.text.slice(0,100000),attempts }); return response; } catch (error) { const latency=Date.now()-attemptStarted; lastError=error instanceof Error?error.message:"Provider request failed."; attempts.push({provider,model,status:"failed",latencyMs:latency,error:lastError}); await updateHealth(provider,{success:false,model,latencyMs:latency,error:lastError}); }
  }
  await logRequest(input,{request_id:requestId,provider_used:null,model:null,status:"failed",fallback_count:Math.max(0,attempts.length-1),latency_ms:Date.now()-started,error_message:lastError.slice(0,2000),attempts}); throw new Error(`All real AI providers failed. ${lastError}`);
}

export async function providerStatuses() { const admin=createAdminClient(); const {data:stored}=await admin.from("ai_provider_health_checks").select("provider,status,model,last_checked_at,last_success_at,last_failure_at,last_latency_ms,consecutive_failures,last_error,total_requests,total_failures"); const map=new Map((stored??[]).map(item=>[item.provider,item])); return supported.map(provider=>{const definition=getProvider(provider)!;const config=definition.health();const item=map.get(provider);return{provider,name:definition.definition.name,configured:config.status==="ready",missing:config.missing,defaultModel:modelFor(provider),status:config.status!=="ready"?"missing_credentials":item?.status??"ready",lastCheckedAt:item?.last_checked_at??null,lastSuccessAt:item?.last_success_at??null,lastFailureAt:item?.last_failure_at??null,latencyMs:item?.last_latency_ms??null,consecutiveFailures:item?.consecutive_failures??0,lastError:item?.last_error??null,totalRequests:item?.total_requests??0,totalFailures:item?.total_failures??0};}); }
