import { NextResponse } from "next/server";

import { resolvePlatformAdmin } from "@/lib/enterprise/admin-auth";
import { evaluateLaunchReadiness } from "@/lib/launch-readiness/engine";
import type { LaunchReport } from "@/lib/launch-readiness/types";
import { createAdminClient } from "@/lib/supabase/admin";

export async function GET() { const access = await resolvePlatformAdmin(); if (!access.ok) return NextResponse.json({ error: access.error }, { status: access.status }); try { const admin = createAdminClient(); const [readiness, reports] = await Promise.all([evaluateLaunchReadiness(), admin.from("launch_readiness_reports").select("id,score,verdict,generated_at,generated_by,missing_configuration").order("generated_at", { ascending: false }).limit(20)]); if (reports.error) throw reports.error; return NextResponse.json({ readiness, reports: (reports.data ?? []) as LaunchReport[] }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Launch evaluation failed." }, { status: 500 }); } }
export async function POST() { const access = await resolvePlatformAdmin(); if (!access.ok) return NextResponse.json({ error: access.error }, { status: access.status }); try { const readiness = await evaluateLaunchReadiness(); const admin = createAdminClient(); const { data: report, error } = await admin.from("launch_readiness_reports").insert({ score: readiness.score, verdict: readiness.verdict, checks: readiness.checks, missing_configuration: readiness.missingConfiguration, summary: readiness.summary, generated_by: access.user.id }).select("id,score,verdict,generated_at,generated_by,missing_configuration").single(); if (error) throw error; await admin.from("enterprise_audit_logs").insert({ actor_id: access.user.id, actor_role: access.role, action: "go_live_report_generated", target_type: "platform", target_id: report.id, metadata: { score: readiness.score, verdict: readiness.verdict, blocked: readiness.summary.blocked } }); return NextResponse.json({ readiness, report }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Go-live report generation failed." }, { status: 500 }); } }
