import{supabase}from"@/lib/supabase";import type{AiRecommendation,Lead,Notification,Project,SocialPost}from"@/lib/types";
function required<T>(data:T|null,error:{message:string}|null){if(error)throw new Error(error.message);return data as T}
export async function getProjects(organizationId:string){const{data,error}=await supabase.from("client_projects").select("id,organization_id,client_name,client_email,project_title,project_description,status,priority,budget,deadline,assigned_member_name,updated_at").eq("organization_id",organizationId).order("updated_at",{ascending:false});return required(data,error)as Project[]}
export async function getProject(projectId:string){const[project,files,messages]=await Promise.all([supabase.from("client_projects").select("*").eq("id",projectId).single(),supabase.from("project_files").select("id,file_name,file_size,file_type,created_at").eq("project_id",projectId).order("created_at",{ascending:false}),supabase.from("project_messages").select("id,sender_name,sender_type,message,created_at").eq("project_id",projectId).order("created_at")]);return{project:required(project.data,project.error),files:required(files.data,files.error),messages:required(messages.data,messages.error)}}
export async function getLeads(organizationId:string){const{data,error}=await supabase.from("leads").select("id,organization_id,name,email,phone,source,budget,notes,status,updated_at").eq("organization_id",organizationId).order("updated_at",{ascending:false});return required(data,error)as Lead[]}
export async function createLead(organizationId:string,input:Partial<Lead>){const{data:{user}}=await supabase.auth.getUser();const{data,error}=await supabase.from("leads").insert({organization_id:organizationId,name:input.name,email:input.email||null,phone:input.phone||null,source:input.source||"mobile",budget:Number(input.budget??0),notes:input.notes||null,status:"new",created_by:user?.id}).select().single();return required(data,error)}
export async function updateLead(id:string,status:string){const{error}=await supabase.from("leads").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error}
export async function getNotifications(organizationId:string,userId:string){const{data,error}=await supabase.from("notifications").select("id,title,message,type,is_read,created_at,project_id").eq("organization_id",organizationId).eq("user_id",userId).order("created_at",{ascending:false}).limit(50);return required(data,error)as Notification[]}
export async function markNotification(id:string){const{error}=await supabase.from("notifications").update({is_read:true}).eq("id",id);if(error)throw error}
export async function getAiTeam(organizationId:string){const[agents,recommendations,tasks]=await Promise.all([supabase.from("ai_agents").select("id,agent_type,name,description,status,last_run_at").eq("organization_id",organizationId),supabase.from("ai_recommendations").select("id,title,recommendation,score,severity,agent_id").eq("organization_id",organizationId).eq("status","open").order("created_at",{ascending:false}),supabase.from("ai_tasks").select("id,title,description,priority,status,agent_id").eq("organization_id",organizationId).in("status",["suggested","accepted"])]);return{agents:required(agents.data,agents.error),recommendations:required(recommendations.data,recommendations.error)as AiRecommendation[],tasks:required(tasks.data,tasks.error)}}
export async function getPublishing(organizationId:string){const[accounts,posts,schedules,metrics]=await Promise.all([supabase.from("social_accounts").select("id,platform,account_name,status").eq("organization_id",organizationId),supabase.from("social_posts").select("id,platform,caption,status,created_at").eq("organization_id",organizationId).order("created_at",{ascending:false}).limit(50),supabase.from("social_schedules").select("id,post_id,scheduled_for,status").eq("organization_id",organizationId).order("scheduled_for"),supabase.from("social_metrics").select("post_id,impressions,views,likes,comments,shares,engagement_rate").eq("organization_id",organizationId)]);return{accounts:required(accounts.data,accounts.error),posts:required(posts.data,posts.error)as SocialPost[],schedules:required(schedules.data,schedules.error),metrics:required(metrics.data,metrics.error)}}
export async function getDashboard(organizationId:string,userId:string){const[projects,leads,invoices,notifications]=await Promise.all([getProjects(organizationId),getLeads(organizationId),supabase.from("project_invoices").select("amount,status").eq("organization_id",organizationId),getNotifications(organizationId,userId)]);const invoiceRows=required(invoices.data,invoices.error);return{activeProjects:projects.filter(item=>!["delivered","archived"].includes(item.status)).length,activeClients:new Set(projects.filter(item=>!["delivered","archived"].includes(item.status)).map(item=>item.client_email||item.client_name)).size,openLeads:leads.filter(item=>!["won","lost"].includes(item.status)).length,revenue:invoiceRows.filter(item=>item.status==="paid").reduce((sum,item)=>sum+Number(item.amount),0),unpaid:invoiceRows.filter(item=>["pending","partially_paid"].includes(item.status)).reduce((sum,item)=>sum+Number(item.amount),0),unread:notifications.filter(item=>!item.is_read).length,recentProjects:projects.slice(0,4)}}
