import { createHmac,timingSafeEqual } from "node:crypto";
import { NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { decryptSecret,hashToken } from "@/lib/whatsapp/crypto";
import { normalizePhone,sendWhatsAppText,suggestWhatsAppReply } from "@/lib/whatsapp/service";
import { clientCommands } from "@/lib/whatsapp/types";

export const runtime="nodejs";
export async function GET(request:Request){const url=new URL(request.url);const mode=url.searchParams.get("hub.mode");const token=url.searchParams.get("hub.verify_token")??"";const challenge=url.searchParams.get("hub.challenge")??"";if(mode!=="subscribe"||!token)return new NextResponse("Forbidden",{status:403});const admin=createAdminClient();const{data}=await admin.from("whatsapp_connections").select("id").eq("verify_token_hash",hashToken(token)).eq("status","active").maybeSingle();return data?new NextResponse(challenge,{status:200}):new NextResponse("Forbidden",{status:403});}

type WebhookValue={metadata?:{phone_number_id?:string};contacts?:Array<{wa_id?:string;profile?:{name?:string}}>;messages?:Array<{id:string;from:string;timestamp:string;type:string;text?:{body?:string}}> ;statuses?:Array<{id:string;status:string;timestamp:string;errors?:Array<{title?:string}>}>};
function signatureValid(raw:string,signature:string|null,secret:string){if(!signature?.startsWith("sha256="))return false;const expected=createHmac("sha256",secret).update(raw).digest("hex");const actual=signature.slice(7);return expected.length===actual.length&&timingSafeEqual(Buffer.from(expected),Buffer.from(actual));}
async function commandResponse(organizationId:string,phone:string,command:string){const admin=createAdminClient();const{data:leads}=await admin.from("leads").select("id,converted_project_id,phone").eq("organization_id",organizationId).order("updated_at",{ascending:false});const lead=(leads??[]).find(item=>normalizePhone(item.phone??"")===phone);let projectId=lead?.converted_project_id??null;if(!projectId){const{data:projects}=await admin.from("client_projects").select("id,client_phone").eq("organization_id",organizationId).order("updated_at",{ascending:false});projectId=(projects??[]).find(item=>normalizePhone(item.client_phone??"")===phone)?.id??null;}if(!projectId)return "I couldn't find a project linked to this number. Please contact your agency support team.";const{data:project}=await admin.from("client_projects").select("id,project_title,status,deadline,updated_at").eq("id",projectId).single();if(!project)return "Your project could not be found.";if(command==="status")return `${project.project_title}: ${String(project.status).replaceAll("_"," ")}. Last updated ${new Date(project.updated_at).toLocaleDateString()}.`;if(command==="progress"){const progress:Record<string,number>={brief:10,planning:25,scripting:40,production:60,review:80,approved:90,delivered:100};return `${project.project_title} is approximately ${progress[project.status]??10}% complete (${String(project.status).replaceAll("_"," ")}).${project.deadline?` Target date: ${new Date(project.deadline).toLocaleDateString()}.`:""}`;}if(command==="invoice"){const{data:invoice}=await admin.from("project_invoices").select("invoice_number,amount,currency,status,issued_at").eq("project_id",projectId).order("issued_at",{ascending:false}).limit(1).maybeSingle();return invoice?`${invoice.invoice_number??"Latest invoice"}: ${invoice.currency} ${invoice.amount} — ${String(invoice.status).replaceAll("_"," ")}.`:"No invoice has been issued for this project yet.";}const[{count},{data:access}]=await Promise.all([admin.from("project_files").select("id",{count:"exact",head:true}).eq("project_id",projectId),admin.from("client_project_access").select("access_token").eq("project_id",projectId).eq("status","active").order("created_at",{ascending:false}).limit(1).maybeSingle()]);const base=process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/,"")??"";return `${count??0} files are available for ${project.project_title}.${access?.access_token&&base?` Open your portal: ${base}/client/project/${access.access_token}`:" Ask your agency for the portal link."}`;}

export async function POST(request:Request){const raw=await request.text();let payload:{entry?:Array<{changes?:Array<{value?:WebhookValue}>}>};try{payload=JSON.parse(raw) as typeof payload;}catch{return NextResponse.json({error:"Invalid payload."},{status:400});}const values=(payload.entry??[]).flatMap(entry=>(entry.changes??[]).map(change=>change.value).filter(Boolean) as WebhookValue[]);const phoneNumberId=values.find(value=>value.metadata?.phone_number_id)?.metadata?.phone_number_id;if(!phoneNumberId)return NextResponse.json({received:true});const admin=createAdminClient();const{data:connection}=await admin.from("whatsapp_connections").select("id,organization_id,app_secret_encrypted,status").eq("phone_number_id",phoneNumberId).eq("status","active").maybeSingle();if(!connection?.app_secret_encrypted)return new NextResponse("Forbidden",{status:403});const secret=decryptSecret(connection.app_secret_encrypted);if(!signatureValid(raw,request.headers.get("x-hub-signature-256"),secret))return new NextResponse("Forbidden",{status:403});
  for(const value of values){for(const status of value.statuses??[]){const mapped=["sent","delivered","read","failed"].includes(status.status)?status.status:"sent";await admin.from("whatsapp_messages").update({status:mapped,delivered_at:mapped==="delivered"?new Date(Number(status.timestamp)*1000).toISOString():undefined,read_at:mapped==="read"?new Date(Number(status.timestamp)*1000).toISOString():undefined,error_message:status.errors?.[0]?.title??null}).eq("whatsapp_message_id",status.id);}for(const message of value.messages??[]){const phone=normalizePhone(message.from);const body=message.text?.body??`[${message.type} message]`;const contactName=value.contacts?.find(contact=>normalizePhone(contact.wa_id??"")===phone)?.profile?.name??null;const suggestion=suggestWhatsAppReply(body);const{error}=await admin.from("whatsapp_messages").insert({organization_id:connection.organization_id,connection_id:connection.id,whatsapp_message_id:message.id,direction:"inbound",message_type:message.type,contact_phone:phone,contact_name:contactName,body,status:"received",metadata:{suggestedReply:suggestion.reply,followUpSuggestion:suggestion.followUp}});if(error&&error.code!=="23505")console.error("[whatsapp] inbound save failed",error);const command=body.trim().toLowerCase();if((clientCommands as readonly string[]).includes(command)){const response=await commandResponse(connection.organization_id,phone,command);await sendWhatsAppText({organizationId:connection.organization_id,to:phone,body:response,contactName,triggerEvent:`client_command_${command}`});}await admin.from("team_activity_logs").insert({organization_id:connection.organization_id,user_id:null,action:"whatsapp_message_received",metadata:{messageId:message.id,phone,command:(clientCommands as readonly string[]).includes(command)?command:null}});}}await admin.from("whatsapp_connections").update({last_webhook_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",connection.id);return NextResponse.json({received:true});}
