import "server-only";

import { getProvider } from "@/lib/providers/provider-registry";
import { createAdminClient } from "@/lib/supabase/admin";
import type { LaunchReadiness, ReadinessCheck, ReadinessStatus } from "@/lib/launch-readiness/types";

const present = (name: string) => Boolean(process.env[name]?.trim());
function check(input: { id: string; category: string; name: string; weight: number; status: ReadinessStatus; summary: string; details?: string[]; missing?: string[]; action?: string | null }): ReadinessCheck { const factor = input.status === "ready" ? 1 : input.status === "warning" ? .5 : 0; return { ...input, points: Math.round(input.weight * factor), details: input.details ?? [], missing: input.missing ?? [], action: input.action ?? null }; }
const missing = (...names: string[]) => names.filter(name => !present(name));

export async function evaluateLaunchReadiness(): Promise<LaunchReadiness> {
  const admin = createAdminClient(); const checks: ReadinessCheck[] = [];
  const supabaseMissing = missing("NEXT_PUBLIC_SUPABASE_URL","NEXT_PUBLIC_SUPABASE_ANON_KEY","SUPABASE_SERVICE_ROLE_KEY"); let databaseOk = false; let databaseDetail = "Database probe did not run.";
  try { const started = Date.now(); const { error, count } = await admin.from("organizations").select("id", { count: "exact", head: true }); if (error) throw error; databaseOk = true; databaseDetail = `Database responded in ${Date.now() - started}ms; ${count ?? 0} organizations visible to the control plane.`; } catch (error) { databaseDetail = error instanceof Error ? error.message : "Database probe failed."; }
  checks.push(check({ id: "supabase", category: "Core", name: "Supabase", weight: 15, status: supabaseMissing.length || !databaseOk ? "blocked" : "ready", summary: databaseOk ? "Database and control-plane credentials are reachable." : "The production database is unreachable.", details: [databaseDetail, "Authenticated tenant access is protected by RLS."], missing: supabaseMissing, action: databaseOk && !supabaseMissing.length ? null : "Configure Supabase production credentials and apply all migrations." }));
  const appMissing = missing("NEXT_PUBLIC_APP_URL"); checks.push(check({ id: "app_url", category: "Core", name: "Production URL", weight: 5, status: appMissing.length ? "blocked" : "ready", summary: appMissing.length ? "Canonical application URL is missing." : `Canonical URL: ${process.env.NEXT_PUBLIC_APP_URL}`, missing: appMissing, action: appMissing.length ? "Set NEXT_PUBLIC_APP_URL to the HTTPS production origin." : null }));
  const securityMissing = missing("CRON_SECRET","HEALTH_CHECK_TOKEN","SECURITY_HASH_SALT"); checks.push(check({ id: "security", category: "Core", name: "Security controls", weight: 5, status: securityMissing.length ? "warning" : "ready", summary: securityMissing.length ? "Core security is enabled, but production secrets are incomplete." : "Cron, health diagnostics, and request hashing are protected.", missing: securityMissing, action: securityMissing.length ? "Generate unique production-only secrets for every missing control." : null }));

  const resendMissing = missing("RESEND_API_KEY","RESEND_FROM_EMAIL"); checks.push(check({ id: "resend", category: "Communications", name: "Resend", weight: 8, status: resendMissing.length ? "warning" : "ready", summary: resendMissing.length ? "Email delivery will use disabled/fallback behavior." : "Transactional email credentials and sender identity are configured.", missing: resendMissing, action: resendMissing.length ? "Verify a sending domain in Resend and configure the API key and From address." : null }));
  const razorpayMissing = missing("RAZORPAY_KEY_ID","RAZORPAY_KEY_SECRET"); const { count: activeSubscriptions } = await admin.from("organization_subscriptions").select("id", { count: "exact", head: true }).in("status", ["active","trialing"]); checks.push(check({ id: "razorpay", category: "Revenue", name: "Razorpay", weight: 10, status: razorpayMissing.length ? "blocked" : "ready", summary: razorpayMissing.length ? "Paid checkout cannot create or verify orders." : "Billing credentials are configured.", details: [`${activeSubscriptions ?? 0} active or trialing workspace subscriptions.`], missing: razorpayMissing, action: razorpayMissing.length ? "Set live Razorpay credentials before accepting payments." : null }));

  const { data: whatsappRows, error: whatsappError } = await admin.from("whatsapp_connections").select("id,status,last_webhook_at").eq("status", "active"); const whatsappReady = !whatsappError && Boolean(whatsappRows?.length); checks.push(check({ id: "whatsapp", category: "Communications", name: "WhatsApp", weight: 8, status: whatsappError ? "blocked" : whatsappReady ? "ready" : "warning", summary: whatsappReady ? `${whatsappRows?.length} active WhatsApp Business connection${whatsappRows?.length === 1 ? "" : "s"}.` : "No active WhatsApp Business connection is available.", details: whatsappRows?.some(row => row.last_webhook_at) ? ["At least one connection has received a webhook."] : ["No webhook heartbeat has been recorded yet."], missing: present("WHATSAPP_ENCRYPTION_KEY") || present("SUPABASE_SERVICE_ROLE_KEY") ? [] : ["WHATSAPP_ENCRYPTION_KEY"], action: whatsappReady ? null : "Connect and verify a production WhatsApp phone number and webhook." }));

  for (const provider of ["openai","gemini","claude"] as const) { const health = getProvider(provider)?.health(); const weight = provider === "claude" ? 5 : 7; const envName = provider === "openai" ? "OPENAI_API_KEY" : provider === "gemini" ? "GEMINI_API_KEY" : "CLAUDE_API_KEY or ANTHROPIC_API_KEY"; checks.push(check({ id: provider, category: "AI", name: provider === "openai" ? "OpenAI" : provider === "gemini" ? "Gemini" : "Claude", weight, status: health?.status === "ready" ? "ready" : "warning", summary: health?.status === "ready" ? `${provider} is available to the provider abstraction.` : `${provider} will fall back to local templates or another configured provider.`, missing: health?.missing ?? [envName], action: health?.status === "ready" ? null : `Configure ${envName} for production generation.` })); }

  const oauthConfigs = [{ name: "YouTube", ready: present("GOOGLE_CLIENT_ID") && present("GOOGLE_CLIENT_SECRET") }, { name: "LinkedIn", ready: present("LINKEDIN_CLIENT_ID") && present("LINKEDIN_CLIENT_SECRET") }, { name: "Meta", ready: present("META_APP_ID") && present("META_APP_SECRET") }]; const { data: socialAccounts } = await admin.from("social_accounts").select("platform,status").eq("status", "connected"); const oauthReady = oauthConfigs.filter(item => item.ready).length; checks.push(check({ id: "oauth", category: "Publishing", name: "OAuth integrations", weight: 10, status: oauthReady === oauthConfigs.length ? "ready" : oauthReady ? "warning" : "blocked", summary: `${oauthReady}/${oauthConfigs.length} OAuth provider configurations ready; ${socialAccounts?.length ?? 0} connected social accounts.`, details: oauthConfigs.map(item => `${item.name}: ${item.ready ? "configured" : "missing credentials"}`), missing: [!oauthConfigs[0].ready ? "GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET" : "", !oauthConfigs[1].ready ? "LINKEDIN_CLIENT_ID / LINKEDIN_CLIENT_SECRET" : "", !oauthConfigs[2].ready ? "META_APP_ID / META_APP_SECRET" : ""].filter(Boolean), action: oauthReady === oauthConfigs.length ? null : "Configure missing OAuth applications and production callback URLs." }));

  const mobileConfigured = present("EXPO_EAS_PROJECT_ID") || present("EXPO_PUBLIC_EAS_PROJECT_ID"); const mobileMissing = mobileConfigured ? [] : ["EXPO_EAS_PROJECT_ID / EXPO_PUBLIC_EAS_PROJECT_ID"]; const { count: pushTokens, error: mobileError } = await admin.from("mobile_push_tokens").select("id", { count: "exact", head: true }).eq("enabled", true); checks.push(check({ id: "mobile", category: "Mobile", name: "Mobile", weight: 8, status: mobileError ? "blocked" : mobileMissing.length ? "warning" : "ready", summary: `${pushTokens ?? 0} active mobile push registrations.${mobileMissing.length ? " EAS production project ID is not mirrored in the web environment." : " EAS project configuration is present."}`, missing: mobileMissing, action: mobileMissing.length ? "Set EXPO_EAS_PROJECT_ID and the Expo mobile environment before store builds." : null }));

  let storageStatus: ReadinessStatus = "blocked"; let bucketNames: string[] = []; try { const { data: buckets, error } = await admin.storage.listBuckets(); if (error) throw error; bucketNames = buckets.map(bucket => bucket.name); storageStatus = ["project-files","workspace-branding"].every(name => bucketNames.includes(name)) ? "ready" : "warning"; } catch { storageStatus = "blocked"; } checks.push(check({ id: "storage", category: "Infrastructure", name: "Storage", weight: 7, status: storageStatus, summary: storageStatus === "ready" ? "Required production buckets are available." : "One or more required storage buckets are missing or unreachable.", details: [`Buckets detected: ${bucketNames.join(", ") || "none"}`], missing: ["project-files","workspace-branding"].filter(name => !bucketNames.includes(name)), action: storageStatus === "ready" ? null : "Apply storage migrations and verify bucket policies, limits, and uploads." }));

  const opsMissing = missing("SENTRY_DSN","UPSTASH_REDIS_REST_URL","UPSTASH_REDIS_REST_TOKEN"); const { data: crons } = await admin.from("cron_monitors").select("name,status,last_completed_at"); const failedCrons = crons?.filter(row => row.status === "failed").length ?? 0; checks.push(check({ id: "operations", category: "Operations", name: "Monitoring & operations", weight: 5, status: failedCrons ? "blocked" : opsMissing.length ? "warning" : "ready", summary: failedCrons ? `${failedCrons} cron monitors are failing.` : "Health, security, queue, and cron monitoring are enabled.", details: [`${crons?.length ?? 0} cron monitors registered.`, `Sentry: ${present("SENTRY_DSN") || present("NEXT_PUBLIC_SENTRY_DSN") ? "configured" : "not configured"}`, `Distributed rate limiting: ${present("UPSTASH_REDIS_REST_URL") && present("UPSTASH_REDIS_REST_TOKEN") ? "configured" : "using instance fallback"}`], missing: opsMissing, action: failedCrons ? "Resolve failed cron jobs before launch." : opsMissing.length ? "Configure external error monitoring and distributed rate limiting." : null }));

  const score = checks.reduce((sum, item) => sum + item.points, 0); const verdict = score >= 85 && !checks.some(item => item.status === "blocked" && ["supabase","app_url","razorpay","storage"].includes(item.id)) ? "production_ready" : score >= 70 ? "conditional" : "blocked"; const missingConfiguration = [...new Set(checks.flatMap(item => item.missing))];
  return { score, verdict, generatedAt: new Date().toISOString(), checks, missingConfiguration, summary: { ready: checks.filter(item => item.status === "ready").length, warning: checks.filter(item => item.status === "warning").length, blocked: checks.filter(item => item.status === "blocked").length, total: checks.length }, services: Object.fromEntries(checks.map(item => [item.id, item.status])) };
}
