import{randomUUID}from"node:crypto";import{NextResponse}from"next/server";import{createAdminClient}from"@/lib/supabase/admin";import{generateSocialCopy,publishDueSocialPosts,publishSocialPost,syncSocialMetrics}from"@/lib/social/publishing";import{isSocialPlatform}from"@/lib/social/types";import{permissionError,resolvePermission}from"@/lib/team/permission-guards";
const clean=(value:unknown,max=5000)=>typeof value==="string"?value.trim().slice(0,max):"";
async function load(organizationId:string){const admin=createAdminClient();const[accounts,posts,schedules,metrics]=await Promise.all([admin.from("social_accounts").select("id,platform,external_account_id,account_name,status,token_expires_at,created_at,updated_at").eq("organization_id",organizationId).order("platform"),admin.from("social_posts").select("id,account_id,project_id,bulk_group_id,platform,title,caption,hashtags,cta,media_url,media_type,status,external_post_id,external_url,error_message,published_at,created_at,updated_at").eq("organization_id",organizationId).order("created_at",{ascending:false}).limit(200),admin.from("social_schedules").select("id,post_id,scheduled_for,timezone,status,attempts,error_message,created_at").eq("organization_id",organizationId).order("scheduled_for").limit(200),admin.from("social_metrics").select("id,post_id,platform,impressions,reach,views,likes,comments,shares,clicks,engagement_rate,synced_at").eq("organization_id",organizationId).order("synced_at",{ascending:false}).limit(200)]);return{accounts:accounts.data??[],posts:posts.data??[],schedules:schedules.data??[],metrics:metrics.data??[]};}
export async function GET(request:Request){const organizationId=new URL(request.url).searchParams.get("organizationId");const access=await resolvePermission("content:edit",organizationId);if(!access.ok)return permissionError(access);return NextResponse.json({...await load(access.organizationId),canConfigure:["owner","admin"].includes(access.role)});}
type Item={platform?:unknown;scheduledFor?:unknown;title?:unknown;caption?:unknown;hashtags?:unknown;cta?:unknown;mediaUrl?:unknown;mediaType?:unknown;accountId?:unknown};
async function createOne(admin:ReturnType<typeof createAdminClient>,organizationId:string,userId:string,item:Item,mode:string,bulkGroupId:string|null){if(!isSocialPlatform(item.platform))throw new Error("Invalid platform.");const{data:account}=await admin.from("social_accounts").select("id").eq("organization_id",organizationId).eq("platform",item.platform).eq("status","connected").limit(1).maybeSingle();if(!account)throw new Error(`${item.platform} is not connected.`);const scheduledFor=clean(item.scheduledFor,64);if(mode==="schedule"&&(!scheduledFor||Date.parse(scheduledFor)<=Date.now()))throw new Error("Schedule time must be in the future.");const hashtags=Array.isArray(item.hashtags)?item.hashtags.map(value=>clean(value,80)).filter(Boolean):clean(item.hashtags).split(/\s+/).filter(Boolean);const mediaType=["text","image","video","reel","short"].includes(String(item.mediaType))?String(item.mediaType):"text";const{data:post,error}=await admin.from("social_posts").insert({organization_id:organizationId,account_id:account.id,bulk_group_id:bulkGroupId,platform:item.platform,title:clean(item.title,200)||null,caption:clean(item.caption),hashtags,cta:clean(item.cta,500)||null,media_url:clean(item.mediaUrl,2000)||null,media_type:mediaType,status:mode==="schedule"?"scheduled":"draft",created_by:userId}).select("id").single();if(error)throw error;if(mode==="schedule"){const{error:scheduleError}=await admin.from("social_schedules").insert({organization_id:organizationId,post_id:post.id,scheduled_for:new Date(scheduledFor).toISOString(),timezone:"UTC"});if(scheduleError)throw scheduleError;}if(mode==="publish")await publishSocialPost(post.id);return post.id;}
export async function POST(request:Request){const body=await request.json().catch(()=>({}))as Record<string,unknown>;const organizationId=clean(body.organizationId,64);const operation=clean(body.operation,40);const permission=operation==="disconnect"?"settings:manage":"content:edit";const access=await resolvePermission(permission,organizationId);if(!access.ok)return permissionError(access);const admin=createAdminClient();
  if(operation==="ai_copy"){const platform=isSocialPlatform(body.platform)?body.platform:"instagram";return NextResponse.json(generateSocialCopy(clean(body.topic,500),clean(body.tone,30),platform));}
  if(operation==="create"){const platforms=Array.isArray(body.platforms)?body.platforms.filter(isSocialPlatform):[];const mode=["draft","schedule","publish"].includes(String(body.mode))?String(body.mode):"draft";if(!platforms.length)return NextResponse.json({error:"Select at least one platform."},{status:400});const group=platforms.length>1?randomUUID():null;const ids=[];try{for(const platform of platforms)ids.push(await createOne(admin,organizationId,access.user.id,{...body,platform},mode,group));}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Post creation failed."},{status:400});}await admin.from("team_activity_logs").insert({organization_id:organizationId,user_id:access.user.id,action:mode==="publish"?"social_post_published":mode==="schedule"?"social_post_scheduled":"social_post_created",metadata:{postIds:ids,platforms,bulkGroupId:group}});return NextResponse.json({success:true,ids});}
  if(operation==="bulk"){const items=Array.isArray(body.items)?body.items as Item[]:[];if(!items.length||items.length>50)return NextResponse.json({error:"Bulk scheduling supports 1–50 posts."},{status:400});const group=randomUUID();const ids=[];try{for(const item of items)ids.push(await createOne(admin,organizationId,access.user.id,item,"schedule",group));}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Bulk scheduling failed."},{status:400});}await admin.from("team_activity_logs").insert({organization_id:organizationId,user_id:access.user.id,action:"social_bulk_scheduled",metadata:{postIds:ids,count:ids.length,bulkGroupId:group}});return NextResponse.json({success:true,ids});}
  if(operation==="sync_metrics"){const synced=await syncSocialMetrics(organizationId);await admin.from("team_activity_logs").insert({organization_id:organizationId,user_id:access.user.id,action:"social_metrics_synced",metadata:{synced}});return NextResponse.json({success:true,synced});}
  if(operation==="run_due"){const results=await publishDueSocialPosts(organizationId);return NextResponse.json({success:true,results});}
  if(operation==="disconnect"){const accountId=clean(body.accountId,64);await admin.from("social_accounts").update({status:"disconnected",updated_at:new Date().toISOString()}).eq("id",accountId).eq("organization_id",organizationId);await admin.from("team_activity_logs").insert({organization_id:organizationId,user_id:access.user.id,action:"social_account_disconnected",metadata:{accountId}});return NextResponse.json({success:true});}
  return NextResponse.json({error:"Unsupported operation."},{status:400});}
