"use client";

import { useCallback,useEffect,useMemo,useState,type FormEvent } from "react";
import type { AgencySnapshot,AiAgentType } from "@/lib/ai-agency/types";

type Agent={id:string;agent_type:AiAgentType;name:string;description:string;status:string;last_run_at:string|null};
type Recommendation={id:string;agent_id:string|null;title:string;recommendation:string;score:number|null;severity:string;status:string;created_at:string};
type AiTask={id:string;agent_id:string|null;title:string;description:string|null;priority:string;status:string;created_at:string};
type Data={agents:Agent[];snapshot:AgencySnapshot;recommendations:Recommendation[];tasks:AiTask[]};
const sections:Array<{type:AiAgentType;label:string;capability:string}>=[{type:"project_manager",label:"Project Manager",capability:"Project risk scoring"},{type:"sales_agent",label:"Sales Agent",capability:"Lead scoring"},{type:"client_success",label:"Client Success",capability:"Client health scoring"},{type:"content_strategist",label:"Content Strategist",capability:"Content suggestions"},{type:"workspace_copilot",label:"Copilot",capability:"Workspace intelligence"}];
const quickQuestions=["Revenue?","Active clients?","Delayed projects?","Unpaid invoices?","Lead conversion rate?"];

export function AiAgencyDashboard({organizationId}:{organizationId:string}){const[data,setData]=useState<Data|null>(null);const[active,setActive]=useState<AiAgentType>("project_manager");const[loading,setLoading]=useState(true);const[message,setMessage]=useState("");
  const load=useCallback(async()=>{setLoading(true);const response=await fetch(`/api/ai-agency?organizationId=${organizationId}`);const payload=await response.json() as Data&{error?:string};if(response.ok)setData(payload);else setMessage(payload.error??"Unable to load AI employees.");setLoading(false);},[organizationId]);useEffect(()=>{void load();},[load]);
  async function generate(){setLoading(true);const response=await fetch("/api/ai-agency",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organizationId,operation:"generate"})});const payload=await response.json() as Data&{error?:string};if(response.ok){setData(payload);setMessage("Fresh recommendations generated from current workspace data.");}else setMessage(payload.error??"Generation failed.");setLoading(false);}
  async function update(operation:string,id:string,status:string){await fetch("/api/ai-agency",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organizationId,operation,id,status})});await load();}
  const agent=data?.agents.find(item=>item.agent_type===active);const recs=useMemo(()=>data?.recommendations.filter(item=>item.agent_id===agent?.id)??[],[data,agent]);const tasks=useMemo(()=>data?.tasks.filter(item=>item.agent_id===agent?.id)??[],[data,agent]);
  return <div><div className="flex flex-col gap-4 rounded-3xl border border-white/10 bg-white/[.035] p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-cyberBlue">Agency intelligence layer</p><p className="mt-2 text-sm text-mist">Scores are explainable and recalculated from live projects, leads, clients, and invoices.</p></div><button onClick={()=>void generate()} disabled={loading} className="rounded-full bg-gradient-to-r from-violetGlow to-cyberBlue px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{loading?"Analyzing…":"Generate recommendations"}</button></div>{message?<p className="mt-4 text-sm text-mist" role="status">{message}</p>:null}
    <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{sections.map(section=>{const item=data?.agents.find(a=>a.agent_type===section.type);return <button key={section.type} onClick={()=>setActive(section.type)} className={`rounded-2xl border p-4 text-left transition ${active===section.type?"border-cyberBlue/50 bg-cyberBlue/[.08]":"border-white/10 bg-white/[.03]"}`}><span className="text-[10px] font-bold uppercase tracking-[.16em] text-cyberBlue">{item?.status??"active"}</span><h2 className="mt-2 font-semibold text-frost">{section.label}</h2><p className="mt-2 text-xs text-mist">{section.capability}</p></button>})}</div>
    {loading&&!data?<p className="mt-5 rounded-3xl border border-white/10 p-10 text-center text-mist">Your AI team is reading the workspace…</p>:null}
    {data&&active!=="workspace_copilot"?<section className="mt-5 grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyberBlue">{agent?.name}</p><h3 className="mt-3 text-2xl font-semibold">Recommendations</h3><p className="mt-2 text-sm text-mist">{agent?.description}</p><div className="mt-5 space-y-3">{recs.length?recs.map(rec=><article key={rec.id} className="rounded-2xl border border-white/10 bg-ink/45 p-4"><div className="flex items-start justify-between gap-3"><div><h4 className="font-semibold text-frost">{rec.title}</h4><p className="mt-2 text-sm leading-6 text-mist">{rec.recommendation}</p></div>{rec.score!==null?<Score value={rec.score}/>:null}</div><div className="mt-3 flex gap-2"><button onClick={()=>void update("recommendation_status",rec.id,"accepted")} className="rounded-full border border-emerald-300/25 px-3 py-1.5 text-xs text-emerald-200">Accept</button><button onClick={()=>void update("recommendation_status",rec.id,"dismissed")} className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-mist">Dismiss</button></div></article>):<p className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-mist">No open recommendations for this employee.</p>}</div></div><div className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><p className="text-xs font-bold uppercase tracking-[.2em] text-violetGlow">Suggested tasks</p><div className="mt-4 space-y-3">{tasks.length?tasks.map(task=><article key={task.id} className="rounded-2xl border border-white/10 bg-ink/45 p-4"><div className="flex justify-between gap-2"><h4 className="text-sm font-semibold">{task.title}</h4><span className="text-[10px] uppercase text-cyberBlue">{task.priority}</span></div><p className="mt-2 text-xs leading-5 text-mist">{task.description}</p><button onClick={()=>void update("task_status",task.id,task.status==="accepted"?"completed":"accepted")} className="mt-3 rounded-full border border-cyberBlue/25 px-3 py-1.5 text-xs text-cyberBlue">{task.status==="accepted"?"Complete":"Accept task"}</button></article>):<p className="text-sm text-mist">No suggested tasks right now.</p>}</div></div></section>:null}
    {data&&active==="workspace_copilot"?<Copilot organizationId={organizationId} snapshot={data.snapshot}/>:null}
    {data?<Scoreboards snapshot={data.snapshot}/>:null}
  </div>;
}
function Score({value}:{value:number}){const color=value>=75?"text-rose-300 border-rose-300/25":value>=55?"text-amber-200 border-amber-200/25":"text-emerald-200 border-emerald-200/25";return <span className={`shrink-0 rounded-full border px-3 py-1 text-xs font-bold ${color}`}>{value}</span>;}
function Copilot({organizationId,snapshot}:{organizationId:string;snapshot:AgencySnapshot}){const[question,setQuestion]=useState("");const[answer,setAnswer]=useState("Ask me about revenue, clients, delivery risk, invoices, or conversion.");const[asking,setAsking]=useState(false);async function ask(value:string){setAsking(true);setQuestion(value);const response=await fetch("/api/ai-agency",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organizationId,operation:"ask",question:value})});const payload=await response.json() as{answer?:string;error?:string};setAnswer(payload.answer??payload.error??"I couldn't answer that.");setAsking(false);}function submit(e:FormEvent){e.preventDefault();if(question.trim())void ask(question);}return <section className="mt-5 grid gap-5 lg:grid-cols-[.65fr_1.35fr]"><div className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyberBlue">Quick questions</p><div className="mt-4 space-y-2">{quickQuestions.map(item=><button key={item} onClick={()=>void ask(item)} className="block w-full rounded-xl border border-white/10 bg-ink/45 px-4 py-3 text-left text-sm text-mist hover:border-cyberBlue/30 hover:text-frost">{item}</button>)}</div></div><div className="rounded-3xl border border-cyberBlue/20 bg-[radial-gradient(circle_at_top_right,rgba(56,189,248,.12),transparent_45%),rgba(255,255,255,.035)] p-5 sm:p-7"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyberBlue">Workspace Copilot</p><div className="mt-5 min-h-32 rounded-2xl border border-white/10 bg-ink/55 p-5 text-lg leading-8 text-frost">{asking?"Reading the workspace…":answer}</div><form onSubmit={submit} className="mt-4 flex gap-2"><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What needs my attention today?" className="workspace-input min-w-0 flex-1 rounded-full border border-white/10 bg-ink/55 px-5 py-3 text-sm text-frost outline-none"/><button className="rounded-full bg-cyberBlue px-5 py-3 text-sm font-bold text-ink">Ask</button></form><p className="mt-3 text-xs text-mist">Live context: {snapshot.activeProjects} projects, {snapshot.activeClients} clients, {snapshot.totalLeads} leads.</p></div></section>}
function Scoreboards({snapshot}:{snapshot:AgencySnapshot}){return <section className="mt-5 grid gap-4 lg:grid-cols-3"><Board title="Highest project risk" rows={snapshot.projectRisks.slice(0,4).map(x=>({name:x.title,detail:x.reason,score:x.score}))}/><Board title="Highest-value leads" rows={snapshot.leadScores.slice(0,4).map(x=>({name:x.name,detail:x.reason,score:x.score}))}/><Board title="Client health watch" rows={snapshot.clientHealth.slice(0,4).map(x=>({name:x.client,detail:x.reason,score:x.score}))}/></section>}
function Board({title,rows}:{title:string;rows:Array<{name:string;detail:string;score:number}>}){return <div className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-cyberBlue">{title}</p><div className="mt-4 space-y-3">{rows.length?rows.map(row=><div key={row.name} className="flex items-center justify-between gap-3 rounded-xl bg-ink/45 p-3"><div className="min-w-0"><p className="truncate text-sm font-semibold">{row.name}</p><p className="mt-1 truncate text-xs text-mist">{row.detail}</p></div><Score value={row.score}/></div>):<p className="text-sm text-mist">No data yet.</p>}</div></div>}
