"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { workflowActions, workflowTriggers, type WorkflowAction, type WorkflowActionType, type WorkflowTrigger } from "@/lib/workflows/types";

type Workflow = { id: string; name: string; description: string | null; trigger_type: WorkflowTrigger; actions: WorkflowAction[]; status: string; updated_at: string };
type Run = { id: string; workflow_id: string; trigger_type: string; status: string; started_at: string; error_message: string | null };
type Log = { id: string; workflow_run_id: string; action_type: string; status: string; error_message: string | null; created_at: string };
type Template = { key: string; name: string; description: string; trigger: WorkflowTrigger; actions: WorkflowAction[] };
type Data = { workflows: Workflow[]; runs: Run[]; logs: Log[]; templates: Template[] };
const emptyData: Data = { workflows: [], runs: [], logs: [], templates: [] };

const actionDefaults: Record<WorkflowActionType, Record<string, unknown>> = {
  create_notification: { recipient: "owner", title: "Automation update", message: "{{projectTitle}} was updated." }, send_email: { recipient: "client", subject: "Project update", message: "There is an update on {{projectTitle}}." }, create_task: { assignee: "assignee", title: "Follow up on {{projectTitle}}" }, update_status: { status: "delivered" }, assign_member: { memberId: "" }, create_activity_log: { action: "workflow_activity" }, create_project: { status: "brief" },
};

export function WorkflowBuilder({ organizationId }: { organizationId: string }) {
  const [data, setData] = useState<Data>(emptyData); const [loading, setLoading] = useState(true); const [tab, setTab] = useState<"builder"|"templates"|"history">("builder"); const [editing, setEditing] = useState<Workflow | null>(null); const [message, setMessage] = useState("");
  const load = useCallback(async () => { setLoading(true); const response = await fetch(`/api/workflows?organizationId=${organizationId}`); const payload = await response.json() as Data & { error?: string }; if (response.ok) setData(payload); else setMessage(payload.error ?? "Unable to load workflows."); setLoading(false); }, [organizationId]);
  useEffect(() => { void load(); }, [load]);
  async function mutate(payload: Record<string, unknown>) { setMessage(""); const response = await fetch("/api/workflows", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ organizationId, ...payload }) }); const result = await response.json() as { error?: string }; setMessage(response.ok ? "Workflow saved." : result.error ?? "Unable to save workflow."); if (response.ok) { setEditing(null); await load(); } }
  return <div>
    <div className="mb-5 flex gap-2 overflow-x-auto">{(["builder","templates","history"] as const).map(item => <button key={item} onClick={() => setTab(item)} className={`rounded-full px-5 py-2.5 text-sm font-semibold capitalize ${tab === item ? "bg-cyberBlue text-ink" : "border border-white/10 text-mist"}`}>{item}</button>)}</div>
    {message ? <p className="mb-4 rounded-xl border border-white/10 bg-white/[.04] p-3 text-sm text-mist" role="status">{message}</p> : null}
    {loading ? <p className="rounded-3xl border border-white/10 p-8 text-center text-mist">Loading automations…</p> : null}
    {!loading && tab === "builder" ? <div className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><WorkflowForm initial={editing} onSave={mutate} onCancel={() => setEditing(null)} /><div className="space-y-3">{data.workflows.length ? data.workflows.map(workflow => <article key={workflow.id} className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="font-semibold text-frost">{workflow.name}</h3><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase ${workflow.status === "active" ? "bg-emerald-300/10 text-emerald-200" : "bg-white/[.06] text-mist"}`}>{workflow.status}</span></div><p className="mt-2 text-sm text-mist">{workflow.trigger_type.replaceAll("_", " ")} → {workflow.actions.map(a => a.type.replaceAll("_", " ")).join(" → ")}</p></div><button onClick={() => setEditing(workflow)} className="text-xs font-semibold text-cyberBlue">Edit</button></div><div className="mt-4 flex gap-2"><button onClick={() => void mutate({ operation:"status", id:workflow.id, status: workflow.status === "active" ? "paused" : "active" })} className="rounded-full border border-cyberBlue/30 px-3 py-1.5 text-xs text-cyberBlue">{workflow.status === "active" ? "Pause" : "Activate"}</button><button onClick={() => void mutate({ operation:"status", id:workflow.id, status:"archived" })} className="rounded-full border border-rose-300/20 px-3 py-1.5 text-xs text-rose-200">Archive</button></div></article>) : <p className="rounded-2xl border border-dashed border-white/10 p-6 text-sm text-mist">No workflows yet. Build one or install a template.</p>}</div></div> : null}
    {!loading && tab === "templates" ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.templates.map(template => <article key={template.key} className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-cyberBlue">{template.trigger.replaceAll("_", " ")}</p><h3 className="mt-3 text-xl font-semibold">{template.name}</h3><p className="mt-3 min-h-12 text-sm leading-6 text-mist">{template.description}</p><p className="mt-4 text-xs text-mist">Action: {template.actions.map(a => a.type.replaceAll("_", " ")).join(", ")}</p><button onClick={() => void mutate({ operation:"template", templateKey:template.key })} className="mt-5 rounded-full bg-cyberBlue px-4 py-2 text-xs font-bold text-ink">Use template</button></article>)}</div> : null}
    {!loading && tab === "history" ? <RunHistory runs={data.runs} logs={data.logs} workflows={data.workflows} /> : null}
  </div>;
}

function WorkflowForm({ initial, onSave, onCancel }: { initial: Workflow | null; onSave: (payload: Record<string, unknown>) => Promise<void>; onCancel: () => void }) {
  const [name, setName] = useState(initial?.name ?? ""); const [description, setDescription] = useState(initial?.description ?? ""); const [trigger, setTrigger] = useState<WorkflowTrigger>(initial?.trigger_type ?? "project_created"); const [actionType, setActionType] = useState<WorkflowActionType>(initial?.actions[0]?.type ?? "create_notification"); const [config, setConfig] = useState(() => JSON.stringify(initial?.actions[0]?.config ?? actionDefaults.create_notification, null, 2));
  useEffect(() => { setName(initial?.name ?? ""); setDescription(initial?.description ?? ""); setTrigger(initial?.trigger_type ?? "project_created"); const type = initial?.actions[0]?.type ?? "create_notification"; setActionType(type); setConfig(JSON.stringify(initial?.actions[0]?.config ?? actionDefaults[type], null, 2)); }, [initial]);
  async function submit(event: FormEvent) { event.preventDefault(); try { await onSave({ id:initial?.id, name, description, triggerType:trigger, actions:[{ type:actionType, config:JSON.parse(config) as Record<string, unknown> }] }); } catch { /* JSON error is shown by native alert below */ setConfig(config); } }
  const input = "workspace-input mt-2 w-full rounded-xl border border-white/10 bg-ink/55 px-3 py-3 text-sm text-frost outline-none";
  return <form onSubmit={submit} className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyberBlue">{initial ? "Edit workflow" : "New workflow"}</p><label className="mt-5 block text-sm text-frost">Name<input required value={name} onChange={e => setName(e.target.value)} className={input} placeholder="Notify team on approval" /></label><label className="mt-4 block text-sm text-frost">Description<input value={description} onChange={e => setDescription(e.target.value)} className={input} /></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm text-frost">Trigger<select value={trigger} onChange={e => setTrigger(e.target.value as WorkflowTrigger)} className={input}>{workflowTriggers.map(item => <option key={item}>{item}</option>)}</select></label><label className="text-sm text-frost">Action<select value={actionType} onChange={e => { const type = e.target.value as WorkflowActionType; setActionType(type); setConfig(JSON.stringify(actionDefaults[type], null, 2)); }} className={input}>{workflowActions.map(item => <option key={item}>{item}</option>)}</select></label></div><label className="mt-4 block text-sm text-frost">Action configuration (JSON)<textarea required rows={7} value={config} onChange={e => setConfig(e.target.value)} className={`${input} font-mono text-xs`} /></label><div className="mt-5 flex gap-2"><button className="rounded-full bg-cyberBlue px-5 py-2.5 text-sm font-bold text-ink">{initial ? "Update" : "Create paused"}</button>{initial ? <button type="button" onClick={onCancel} className="rounded-full border border-white/10 px-5 py-2.5 text-sm text-mist">Cancel</button> : null}</div></form>;
}
function RunHistory({ runs, logs, workflows }: { runs: Run[]; logs: Log[]; workflows: Workflow[] }) { const names = new Map(workflows.map(w => [w.id,w.name])); return <div className="overflow-hidden rounded-3xl border border-white/10 bg-white/[.03]"><div className="grid grid-cols-[1.2fr_1fr_.7fr_1fr] gap-3 bg-white/[.04] px-5 py-3 text-xs font-bold uppercase tracking-[.14em] text-mist"><span>Workflow / trigger</span><span>Action</span><span>Result</span><span>Timestamp</span></div>{runs.length ? runs.map(run => { const runLogs = logs.filter(log => log.workflow_run_id === run.id); return <div key={run.id} className="grid grid-cols-[1.2fr_1fr_.7fr_1fr] gap-3 border-t border-white/[.08] px-5 py-4 text-sm"><span><b className="block text-frost">{names.get(run.workflow_id) ?? "Archived workflow"}</b><span className="text-xs text-mist">{run.trigger_type}</span></span><span className="text-mist">{runLogs.map(log => log.action_type).join(", ") || "—"}</span><span className={run.status === "success" ? "text-emerald-300" : "text-rose-300"}>{run.status}{run.error_message ? <small className="block">{run.error_message}</small> : null}</span><span className="text-mist">{new Date(run.started_at).toLocaleString()}</span></div> }) : <p className="p-6 text-sm text-mist">Execution history will appear after an active workflow receives a trigger.</p>}</div>; }
